// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api_types.proto

#include "api_types.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace game_api {
namespace v1 {
PROTOBUF_CONSTEXPR ResourceEffect::ResourceEffect(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_type_)*/0
  , /*decltype(_impl_.delta_value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ResourceEffectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResourceEffectDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResourceEffectDefaultTypeInternal() {}
  union {
    ResourceEffect _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResourceEffectDefaultTypeInternal _ResourceEffect_default_instance_;
PROTOBUF_CONSTEXPR Building::Building(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.effects_)*/{}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.build_cost_)*/0
  , /*decltype(_impl_.ticks_to_complete_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BuildingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildingDefaultTypeInternal() {}
  union {
    Building _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildingDefaultTypeInternal _Building_default_instance_;
PROTOBUF_CONSTEXPR Petition::Petition(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.building_)*/nullptr
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PetitionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PetitionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PetitionDefaultTypeInternal() {}
  union {
    Petition _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PetitionDefaultTypeInternal _Petition_default_instance_;
PROTOBUF_CONSTEXPR GameState_BuildingCountsEntry_DoNotUse::GameState_BuildingCountsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    GameState_BuildingCountsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal _GameState_BuildingCountsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR GameState_ResourcesEntry_DoNotUse::GameState_ResourcesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct GameState_ResourcesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameState_ResourcesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameState_ResourcesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    GameState_ResourcesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameState_ResourcesEntry_DoNotUseDefaultTypeInternal _GameState_ResourcesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR GameState::GameState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.building_counts_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.resources_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.current_petition_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameStateDefaultTypeInternal() {}
  union {
    GameState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameStateDefaultTypeInternal _GameState_default_instance_;
PROTOBUF_CONSTEXPR PetitionResponse::PetitionResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.responded_)*/false
  , /*decltype(_impl_.accepted_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PetitionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PetitionResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PetitionResponseDefaultTypeInternal() {}
  union {
    PetitionResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PetitionResponseDefaultTypeInternal _PetitionResponse_default_instance_;
PROTOBUF_CONSTEXPR UIAction::UIAction(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.petition_response_)*/nullptr
  , /*decltype(_impl_.save_game_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UIActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UIActionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UIActionDefaultTypeInternal() {}
  union {
    UIAction _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UIActionDefaultTypeInternal _UIAction_default_instance_;
}  // namespace v1
}  // namespace game_api
static ::_pb::Metadata file_level_metadata_api_5ftypes_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_api_5ftypes_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_api_5ftypes_2eproto = nullptr;

const uint32_t TableStruct_api_5ftypes_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::ResourceEffect, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::ResourceEffect, _impl_.resource_type_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::ResourceEffect, _impl_.delta_value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.build_cost_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.ticks_to_complete_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.effects_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _impl_.building_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_ResourcesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_ResourcesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_ResourcesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_ResourcesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.building_counts_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.resources_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.current_petition_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::PetitionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::PetitionResponse, _impl_.responded_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::PetitionResponse, _impl_.accepted_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _impl_.petition_response_),
  PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _impl_.save_game_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::game_api::v1::ResourceEffect)},
  { 8, -1, -1, sizeof(::game_api::v1::Building)},
  { 18, -1, -1, sizeof(::game_api::v1::Petition)},
  { 26, 34, -1, sizeof(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse)},
  { 36, 44, -1, sizeof(::game_api::v1::GameState_ResourcesEntry_DoNotUse)},
  { 46, -1, -1, sizeof(::game_api::v1::GameState)},
  { 55, -1, -1, sizeof(::game_api::v1::PetitionResponse)},
  { 63, -1, -1, sizeof(::game_api::v1::UIAction)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::game_api::v1::_ResourceEffect_default_instance_._instance,
  &::game_api::v1::_Building_default_instance_._instance,
  &::game_api::v1::_Petition_default_instance_._instance,
  &::game_api::v1::_GameState_BuildingCountsEntry_DoNotUse_default_instance_._instance,
  &::game_api::v1::_GameState_ResourcesEntry_DoNotUse_default_instance_._instance,
  &::game_api::v1::_GameState_default_instance_._instance,
  &::game_api::v1::_PetitionResponse_default_instance_._instance,
  &::game_api::v1::_UIAction_default_instance_._instance,
};

const char descriptor_table_protodef_api_5ftypes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017api_types.proto\022\013game_api.v1\"W\n\016Resour"
  "ceEffect\0220\n\rresource_type\030\001 \001(\0162\031.game_a"
  "pi.v1.ResourceType\022\023\n\013delta_value\030\002 \001(\005\""
  "\220\001\n\010Building\022\'\n\004type\030\001 \001(\0162\031.game_api.v1"
  ".BuildingType\022\022\n\nbuild_cost\030\002 \001(\005\022\031\n\021tic"
  "ks_to_complete\030\003 \001(\005\022,\n\007effects\030\004 \003(\0132\033."
  "game_api.v1.ResourceEffect\"\?\n\010Petition\022\n"
  "\n\002id\030\001 \001(\005\022\'\n\010building\030\002 \001(\0132\025.game_api."
  "v1.Building\"\244\002\n\tGameState\022C\n\017building_co"
  "unts\030\001 \003(\0132*.game_api.v1.GameState.Build"
  "ingCountsEntry\0228\n\tresources\030\005 \003(\0132%.game"
  "_api.v1.GameState.ResourcesEntry\022/\n\020curr"
  "ent_petition\030\004 \001(\0132\025.game_api.v1.Petitio"
  "n\0325\n\023BuildingCountsEntry\022\013\n\003key\030\001 \001(\005\022\r\n"
  "\005value\030\002 \001(\005:\0028\001\0320\n\016ResourcesEntry\022\013\n\003ke"
  "y\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\"7\n\020PetitionRe"
  "sponse\022\021\n\tresponded\030\001 \001(\010\022\020\n\010accepted\030\002 "
  "\001(\010\"W\n\010UIAction\0228\n\021petition_response\030\001 \001"
  "(\0132\035.game_api.v1.PetitionResponse\022\021\n\tsav"
  "e_game\030\002 \001(\010*\366\003\n\014BuildingType\022\035\n\031BUILDIN"
  "G_TYPE_UNSPECIFIED\020\000\022\035\n\031BUILDING_TYPE_PO"
  "WER_PLANT\020\001\022\'\n#BUILDING_TYPE_WATER_TREAT"
  "MENT_PLANT\020\002\022\"\n\036BUILDING_TYPE_SOLAR_PANE"
  "L_FARM\020\003\022&\n\"BUILDING_TYPE_SOLAR_PANEL_RO"
  "OFTOPS\020\004\022*\n&BUILDING_TYPE_PUBLIC_TRANSPO"
  "RT_UPGRADE\020\005\022#\n\037BUILDING_TYPE_WIND_TURBI"
  "NE_FARM\020\006\022%\n!BUILDING_TYPE_HYDROELECTRIC"
  "_PLANT\020\007\022 \n\034BUILDING_TYPE_URBAN_GREENING"
  "\020\010\022-\n)BUILDING_TYPE_WATER_SAVING_INFRAST"
  "RUCTURE\020\t\022!\n\035BUILDING_TYPE_INDUSTRIAL_ZO"
  "NE\020\n\022#\n\037BUILDING_TYPE_AIRPORT_EXPANSION\020"
  "\013\022\"\n\036BUILDING_TYPE_ROAD_IMPROVEMENT\020\014*\256\001"
  "\n\014ResourceType\022\035\n\031RESOURCE_TYPE_UNSPECIF"
  "IED\020\000\022\027\n\023RESOURCE_TYPE_WATER\020\001\022\030\n\024RESOUR"
  "CE_TYPE_ENERGY\020\002\022\027\n\023RESOURCE_TYPE_MONEY\020"
  "\003\022\034\n\030RESOURCE_TYPE_POPULATION\020\004\022\025\n\021RESOU"
  "RCE_TYPE_CO2\020\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_api_5ftypes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_api_5ftypes_2eproto = {
    false, false, 1462, descriptor_table_protodef_api_5ftypes_2eproto,
    "api_types.proto",
    &descriptor_table_api_5ftypes_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_api_5ftypes_2eproto::offsets,
    file_level_metadata_api_5ftypes_2eproto, file_level_enum_descriptors_api_5ftypes_2eproto,
    file_level_service_descriptors_api_5ftypes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_api_5ftypes_2eproto_getter() {
  return &descriptor_table_api_5ftypes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_api_5ftypes_2eproto(&descriptor_table_api_5ftypes_2eproto);
namespace game_api {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BuildingType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_api_5ftypes_2eproto);
  return file_level_enum_descriptors_api_5ftypes_2eproto[0];
}
bool BuildingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResourceType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_api_5ftypes_2eproto);
  return file_level_enum_descriptors_api_5ftypes_2eproto[1];
}
bool ResourceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ResourceEffect::_Internal {
 public:
};

ResourceEffect::ResourceEffect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.ResourceEffect)
}
ResourceEffect::ResourceEffect(const ResourceEffect& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ResourceEffect* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_type_){}
    , decltype(_impl_.delta_value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.resource_type_, &from._impl_.resource_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.delta_value_) -
    reinterpret_cast<char*>(&_impl_.resource_type_)) + sizeof(_impl_.delta_value_));
  // @@protoc_insertion_point(copy_constructor:game_api.v1.ResourceEffect)
}

inline void ResourceEffect::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_type_){0}
    , decltype(_impl_.delta_value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ResourceEffect::~ResourceEffect() {
  // @@protoc_insertion_point(destructor:game_api.v1.ResourceEffect)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResourceEffect::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ResourceEffect::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ResourceEffect::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.ResourceEffect)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.resource_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.delta_value_) -
      reinterpret_cast<char*>(&_impl_.resource_type_)) + sizeof(_impl_.delta_value_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResourceEffect::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .game_api.v1.ResourceType resource_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_resource_type(static_cast<::game_api::v1::ResourceType>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 delta_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.delta_value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ResourceEffect::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.ResourceEffect)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .game_api.v1.ResourceType resource_type = 1;
  if (this->_internal_resource_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_resource_type(), target);
  }

  // int32 delta_value = 2;
  if (this->_internal_delta_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_delta_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.ResourceEffect)
  return target;
}

size_t ResourceEffect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.ResourceEffect)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_api.v1.ResourceType resource_type = 1;
  if (this->_internal_resource_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_resource_type());
  }

  // int32 delta_value = 2;
  if (this->_internal_delta_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_delta_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResourceEffect::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ResourceEffect::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResourceEffect::GetClassData() const { return &_class_data_; }


void ResourceEffect::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ResourceEffect*>(&to_msg);
  auto& from = static_cast<const ResourceEffect&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.ResourceEffect)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_resource_type() != 0) {
    _this->_internal_set_resource_type(from._internal_resource_type());
  }
  if (from._internal_delta_value() != 0) {
    _this->_internal_set_delta_value(from._internal_delta_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResourceEffect::CopyFrom(const ResourceEffect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.ResourceEffect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResourceEffect::IsInitialized() const {
  return true;
}

void ResourceEffect::InternalSwap(ResourceEffect* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.delta_value_)
      + sizeof(ResourceEffect::_impl_.delta_value_)
      - PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.resource_type_)>(
          reinterpret_cast<char*>(&_impl_.resource_type_),
          reinterpret_cast<char*>(&other->_impl_.resource_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ResourceEffect::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[0]);
}

// ===================================================================

class Building::_Internal {
 public:
};

Building::Building(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.Building)
}
Building::Building(const Building& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Building* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.effects_){from._impl_.effects_}
    , decltype(_impl_.type_){}
    , decltype(_impl_.build_cost_){}
    , decltype(_impl_.ticks_to_complete_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ticks_to_complete_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.ticks_to_complete_));
  // @@protoc_insertion_point(copy_constructor:game_api.v1.Building)
}

inline void Building::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.effects_){arena}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.build_cost_){0}
    , decltype(_impl_.ticks_to_complete_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Building::~Building() {
  // @@protoc_insertion_point(destructor:game_api.v1.Building)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Building::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.effects_.~RepeatedPtrField();
}

void Building::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Building::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.Building)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.effects_.Clear();
  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ticks_to_complete_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.ticks_to_complete_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Building::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .game_api.v1.BuildingType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::game_api::v1::BuildingType>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 build_cost = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.build_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 ticks_to_complete = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ticks_to_complete_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .game_api.v1.ResourceEffect effects = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_effects(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Building::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.Building)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .game_api.v1.BuildingType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // int32 build_cost = 2;
  if (this->_internal_build_cost() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_build_cost(), target);
  }

  // int32 ticks_to_complete = 3;
  if (this->_internal_ticks_to_complete() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_ticks_to_complete(), target);
  }

  // repeated .game_api.v1.ResourceEffect effects = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_effects_size()); i < n; i++) {
    const auto& repfield = this->_internal_effects(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.Building)
  return target;
}

size_t Building::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.Building)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .game_api.v1.ResourceEffect effects = 4;
  total_size += 1UL * this->_internal_effects_size();
  for (const auto& msg : this->_impl_.effects_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .game_api.v1.BuildingType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // int32 build_cost = 2;
  if (this->_internal_build_cost() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_build_cost());
  }

  // int32 ticks_to_complete = 3;
  if (this->_internal_ticks_to_complete() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ticks_to_complete());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Building::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Building::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Building::GetClassData() const { return &_class_data_; }


void Building::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Building*>(&to_msg);
  auto& from = static_cast<const Building&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.Building)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.effects_.MergeFrom(from._impl_.effects_);
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_build_cost() != 0) {
    _this->_internal_set_build_cost(from._internal_build_cost());
  }
  if (from._internal_ticks_to_complete() != 0) {
    _this->_internal_set_ticks_to_complete(from._internal_ticks_to_complete());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Building::CopyFrom(const Building& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.Building)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Building::IsInitialized() const {
  return true;
}

void Building::InternalSwap(Building* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.effects_.InternalSwap(&other->_impl_.effects_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Building, _impl_.ticks_to_complete_)
      + sizeof(Building::_impl_.ticks_to_complete_)
      - PROTOBUF_FIELD_OFFSET(Building, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Building::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[1]);
}

// ===================================================================

class Petition::_Internal {
 public:
  static const ::game_api::v1::Building& building(const Petition* msg);
};

const ::game_api::v1::Building&
Petition::_Internal::building(const Petition* msg) {
  return *msg->_impl_.building_;
}
Petition::Petition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.Petition)
}
Petition::Petition(const Petition& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Petition* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.building_){nullptr}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_building()) {
    _this->_impl_.building_ = new ::game_api::v1::Building(*from._impl_.building_);
  }
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:game_api.v1.Petition)
}

inline void Petition::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.building_){nullptr}
    , decltype(_impl_.id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Petition::~Petition() {
  // @@protoc_insertion_point(destructor:game_api.v1.Petition)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Petition::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.building_;
}

void Petition::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Petition::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.Petition)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.building_ != nullptr) {
    delete _impl_.building_;
  }
  _impl_.building_ = nullptr;
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Petition::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .game_api.v1.Building building = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_building(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Petition::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.Petition)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // .game_api.v1.Building building = 2;
  if (this->_internal_has_building()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::building(this),
        _Internal::building(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.Petition)
  return target;
}

size_t Petition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.Petition)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_api.v1.Building building = 2;
  if (this->_internal_has_building()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.building_);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Petition::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Petition::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Petition::GetClassData() const { return &_class_data_; }


void Petition::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Petition*>(&to_msg);
  auto& from = static_cast<const Petition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.Petition)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_building()) {
    _this->_internal_mutable_building()->::game_api::v1::Building::MergeFrom(
        from._internal_building());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Petition::CopyFrom(const Petition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.Petition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Petition::IsInitialized() const {
  return true;
}

void Petition::InternalSwap(Petition* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Petition, _impl_.id_)
      + sizeof(Petition::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Petition, _impl_.building_)>(
          reinterpret_cast<char*>(&_impl_.building_),
          reinterpret_cast<char*>(&other->_impl_.building_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Petition::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[2]);
}

// ===================================================================

GameState_BuildingCountsEntry_DoNotUse::GameState_BuildingCountsEntry_DoNotUse() {}
GameState_BuildingCountsEntry_DoNotUse::GameState_BuildingCountsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void GameState_BuildingCountsEntry_DoNotUse::MergeFrom(const GameState_BuildingCountsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata GameState_BuildingCountsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[3]);
}

// ===================================================================

GameState_ResourcesEntry_DoNotUse::GameState_ResourcesEntry_DoNotUse() {}
GameState_ResourcesEntry_DoNotUse::GameState_ResourcesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void GameState_ResourcesEntry_DoNotUse::MergeFrom(const GameState_ResourcesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata GameState_ResourcesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[4]);
}

// ===================================================================

class GameState::_Internal {
 public:
  static const ::game_api::v1::Petition& current_petition(const GameState* msg);
};

const ::game_api::v1::Petition&
GameState::_Internal::current_petition(const GameState* msg) {
  return *msg->_impl_.current_petition_;
}
GameState::GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &GameState::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:game_api.v1.GameState)
}
GameState::GameState(const GameState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GameState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.building_counts_)*/{}
    , /*decltype(_impl_.resources_)*/{}
    , decltype(_impl_.current_petition_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.building_counts_.MergeFrom(from._impl_.building_counts_);
  _this->_impl_.resources_.MergeFrom(from._impl_.resources_);
  if (from._internal_has_current_petition()) {
    _this->_impl_.current_petition_ = new ::game_api::v1::Petition(*from._impl_.current_petition_);
  }
  // @@protoc_insertion_point(copy_constructor:game_api.v1.GameState)
}

inline void GameState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.building_counts_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_.resources_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.current_petition_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GameState::~GameState() {
  // @@protoc_insertion_point(destructor:game_api.v1.GameState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void GameState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.building_counts_.Destruct();
  _impl_.building_counts_.~MapField();
  _impl_.resources_.Destruct();
  _impl_.resources_.~MapField();
  if (this != internal_default_instance()) delete _impl_.current_petition_;
}

void GameState::ArenaDtor(void* object) {
  GameState* _this = reinterpret_cast< GameState* >(object);
  _this->_impl_.building_counts_.Destruct();
  _this->_impl_.resources_.Destruct();
}
void GameState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GameState::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.GameState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.building_counts_.Clear();
  _impl_.resources_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.current_petition_ != nullptr) {
    delete _impl_.current_petition_;
  }
  _impl_.current_petition_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<int32, int32> building_counts = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.building_counts_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .game_api.v1.Petition current_petition = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_current_petition(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<int32, int32> resources = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.resources_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GameState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.GameState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, int32> building_counts = 1;
  if (!this->_internal_building_counts().empty()) {
    using MapType = ::_pb::Map<int32_t, int32_t>;
    using WireHelper = GameState_BuildingCountsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_building_counts();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    }
  }

  // .game_api.v1.Petition current_petition = 4;
  if (this->_internal_has_current_petition()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::current_petition(this),
        _Internal::current_petition(this).GetCachedSize(), target, stream);
  }

  // map<int32, int32> resources = 5;
  if (!this->_internal_resources().empty()) {
    using MapType = ::_pb::Map<int32_t, int32_t>;
    using WireHelper = GameState_ResourcesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_resources();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(5, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.GameState)
  return target;
}

size_t GameState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.GameState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, int32> building_counts = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_building_counts_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, int32_t >::const_iterator
      it = this->_internal_building_counts().begin();
      it != this->_internal_building_counts().end(); ++it) {
    total_size += GameState_BuildingCountsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<int32, int32> resources = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_resources_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, int32_t >::const_iterator
      it = this->_internal_resources().begin();
      it != this->_internal_resources().end(); ++it) {
    total_size += GameState_ResourcesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .game_api.v1.Petition current_petition = 4;
  if (this->_internal_has_current_petition()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.current_petition_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GameState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameState::GetClassData() const { return &_class_data_; }


void GameState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GameState*>(&to_msg);
  auto& from = static_cast<const GameState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.GameState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.building_counts_.MergeFrom(from._impl_.building_counts_);
  _this->_impl_.resources_.MergeFrom(from._impl_.resources_);
  if (from._internal_has_current_petition()) {
    _this->_internal_mutable_current_petition()->::game_api::v1::Petition::MergeFrom(
        from._internal_current_petition());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameState::CopyFrom(const GameState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.GameState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameState::IsInitialized() const {
  return true;
}

void GameState::InternalSwap(GameState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.building_counts_.InternalSwap(&other->_impl_.building_counts_);
  _impl_.resources_.InternalSwap(&other->_impl_.resources_);
  swap(_impl_.current_petition_, other->_impl_.current_petition_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GameState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[5]);
}

// ===================================================================

class PetitionResponse::_Internal {
 public:
};

PetitionResponse::PetitionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.PetitionResponse)
}
PetitionResponse::PetitionResponse(const PetitionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PetitionResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.responded_){}
    , decltype(_impl_.accepted_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.responded_, &from._impl_.responded_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.accepted_) -
    reinterpret_cast<char*>(&_impl_.responded_)) + sizeof(_impl_.accepted_));
  // @@protoc_insertion_point(copy_constructor:game_api.v1.PetitionResponse)
}

inline void PetitionResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.responded_){false}
    , decltype(_impl_.accepted_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PetitionResponse::~PetitionResponse() {
  // @@protoc_insertion_point(destructor:game_api.v1.PetitionResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PetitionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PetitionResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PetitionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.PetitionResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.responded_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.accepted_) -
      reinterpret_cast<char*>(&_impl_.responded_)) + sizeof(_impl_.accepted_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PetitionResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool responded = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.responded_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool accepted = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.accepted_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PetitionResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.PetitionResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool responded = 1;
  if (this->_internal_responded() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_responded(), target);
  }

  // bool accepted = 2;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_accepted(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.PetitionResponse)
  return target;
}

size_t PetitionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.PetitionResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool responded = 1;
  if (this->_internal_responded() != 0) {
    total_size += 1 + 1;
  }

  // bool accepted = 2;
  if (this->_internal_accepted() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PetitionResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PetitionResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PetitionResponse::GetClassData() const { return &_class_data_; }


void PetitionResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PetitionResponse*>(&to_msg);
  auto& from = static_cast<const PetitionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.PetitionResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_responded() != 0) {
    _this->_internal_set_responded(from._internal_responded());
  }
  if (from._internal_accepted() != 0) {
    _this->_internal_set_accepted(from._internal_accepted());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PetitionResponse::CopyFrom(const PetitionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.PetitionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PetitionResponse::IsInitialized() const {
  return true;
}

void PetitionResponse::InternalSwap(PetitionResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.accepted_)
      + sizeof(PetitionResponse::_impl_.accepted_)
      - PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.responded_)>(
          reinterpret_cast<char*>(&_impl_.responded_),
          reinterpret_cast<char*>(&other->_impl_.responded_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PetitionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[6]);
}

// ===================================================================

class UIAction::_Internal {
 public:
  static const ::game_api::v1::PetitionResponse& petition_response(const UIAction* msg);
};

const ::game_api::v1::PetitionResponse&
UIAction::_Internal::petition_response(const UIAction* msg) {
  return *msg->_impl_.petition_response_;
}
UIAction::UIAction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.UIAction)
}
UIAction::UIAction(const UIAction& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UIAction* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.petition_response_){nullptr}
    , decltype(_impl_.save_game_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_petition_response()) {
    _this->_impl_.petition_response_ = new ::game_api::v1::PetitionResponse(*from._impl_.petition_response_);
  }
  _this->_impl_.save_game_ = from._impl_.save_game_;
  // @@protoc_insertion_point(copy_constructor:game_api.v1.UIAction)
}

inline void UIAction::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.petition_response_){nullptr}
    , decltype(_impl_.save_game_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UIAction::~UIAction() {
  // @@protoc_insertion_point(destructor:game_api.v1.UIAction)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UIAction::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.petition_response_;
}

void UIAction::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UIAction::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.UIAction)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.petition_response_ != nullptr) {
    delete _impl_.petition_response_;
  }
  _impl_.petition_response_ = nullptr;
  _impl_.save_game_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UIAction::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .game_api.v1.PetitionResponse petition_response = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_petition_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool save_game = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.save_game_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UIAction::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.UIAction)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .game_api.v1.PetitionResponse petition_response = 1;
  if (this->_internal_has_petition_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::petition_response(this),
        _Internal::petition_response(this).GetCachedSize(), target, stream);
  }

  // bool save_game = 2;
  if (this->_internal_save_game() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_save_game(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.UIAction)
  return target;
}

size_t UIAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.UIAction)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_api.v1.PetitionResponse petition_response = 1;
  if (this->_internal_has_petition_response()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.petition_response_);
  }

  // bool save_game = 2;
  if (this->_internal_save_game() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UIAction::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UIAction::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UIAction::GetClassData() const { return &_class_data_; }


void UIAction::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UIAction*>(&to_msg);
  auto& from = static_cast<const UIAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.UIAction)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_petition_response()) {
    _this->_internal_mutable_petition_response()->::game_api::v1::PetitionResponse::MergeFrom(
        from._internal_petition_response());
  }
  if (from._internal_save_game() != 0) {
    _this->_internal_set_save_game(from._internal_save_game());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UIAction::CopyFrom(const UIAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.UIAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UIAction::IsInitialized() const {
  return true;
}

void UIAction::InternalSwap(UIAction* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UIAction, _impl_.save_game_)
      + sizeof(UIAction::_impl_.save_game_)
      - PROTOBUF_FIELD_OFFSET(UIAction, _impl_.petition_response_)>(
          reinterpret_cast<char*>(&_impl_.petition_response_),
          reinterpret_cast<char*>(&other->_impl_.petition_response_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UIAction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace game_api
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game_api::v1::ResourceEffect*
Arena::CreateMaybeMessage< ::game_api::v1::ResourceEffect >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::ResourceEffect >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::Building*
Arena::CreateMaybeMessage< ::game_api::v1::Building >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::Building >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::Petition*
Arena::CreateMaybeMessage< ::game_api::v1::Petition >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::Petition >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::GameState_BuildingCountsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::game_api::v1::GameState_BuildingCountsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::GameState_BuildingCountsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::GameState_ResourcesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::game_api::v1::GameState_ResourcesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::GameState_ResourcesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::GameState*
Arena::CreateMaybeMessage< ::game_api::v1::GameState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::GameState >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::PetitionResponse*
Arena::CreateMaybeMessage< ::game_api::v1::PetitionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::PetitionResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::game_api::v1::UIAction*
Arena::CreateMaybeMessage< ::game_api::v1::UIAction >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_api::v1::UIAction >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
