// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api_types.proto
// Protobuf C++ Version: 4.25.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_api_5ftypes_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_api_5ftypes_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025002 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_5ftypes_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_5ftypes_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_api_5ftypes_2eproto;
namespace game_api {
namespace v1 {
class Building;
struct BuildingDefaultTypeInternal;
extern BuildingDefaultTypeInternal _Building_default_instance_;
class GameState;
struct GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class GameState_BuildingCountsEntry_DoNotUse;
struct GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal;
extern GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal _GameState_BuildingCountsEntry_DoNotUse_default_instance_;
class GameState_ResourcesEntry_DoNotUse;
struct GameState_ResourcesEntry_DoNotUseDefaultTypeInternal;
extern GameState_ResourcesEntry_DoNotUseDefaultTypeInternal _GameState_ResourcesEntry_DoNotUse_default_instance_;
class Petition;
struct PetitionDefaultTypeInternal;
extern PetitionDefaultTypeInternal _Petition_default_instance_;
class PetitionResponse;
struct PetitionResponseDefaultTypeInternal;
extern PetitionResponseDefaultTypeInternal _PetitionResponse_default_instance_;
class ResourceEffect;
struct ResourceEffectDefaultTypeInternal;
extern ResourceEffectDefaultTypeInternal _ResourceEffect_default_instance_;
class UIAction;
struct UIActionDefaultTypeInternal;
extern UIActionDefaultTypeInternal _UIAction_default_instance_;
}  // namespace v1
}  // namespace game_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace game_api {
namespace v1 {
enum BuildingType : int {
  BUILDING_TYPE_UNSPECIFIED = 0,
  BUILDING_TYPE_POWER_PLANT = 1,
  BUILDING_TYPE_WATER_TREATMENT_PLANT = 2,
  BUILDING_TYPE_SOLAR_PANEL_FARM = 3,
  BUILDING_TYPE_SOLAR_PANEL_ROOFTOPS = 4,
  BUILDING_TYPE_PUBLIC_TRANSPORT_UPGRADE = 5,
  BUILDING_TYPE_WIND_TURBINE_FARM = 6,
  BUILDING_TYPE_HYDROELECTRIC_PLANT = 7,
  BUILDING_TYPE_URBAN_GREENING = 8,
  BUILDING_TYPE_WATER_SAVING_INFRASTRUCTURE = 9,
  BUILDING_TYPE_INDUSTRIAL_ZONE = 10,
  BUILDING_TYPE_AIRPORT_EXPANSION = 11,
  BUILDING_TYPE_ROAD_IMPROVEMENT = 12,
  BuildingType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  BuildingType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool BuildingType_IsValid(int value);
extern const uint32_t BuildingType_internal_data_[];
constexpr BuildingType BuildingType_MIN = static_cast<BuildingType>(0);
constexpr BuildingType BuildingType_MAX = static_cast<BuildingType>(12);
constexpr int BuildingType_ARRAYSIZE = 12 + 1;
const ::google::protobuf::EnumDescriptor*
BuildingType_descriptor();
template <typename T>
const std::string& BuildingType_Name(T value) {
  static_assert(std::is_same<T, BuildingType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BuildingType_Name().");
  return BuildingType_Name(static_cast<BuildingType>(value));
}
template <>
inline const std::string& BuildingType_Name(BuildingType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<BuildingType_descriptor,
                                                 0, 12>(
      static_cast<int>(value));
}
inline bool BuildingType_Parse(absl::string_view name, BuildingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuildingType>(
      BuildingType_descriptor(), name, value);
}
enum ResourceType : int {
  RESOURCE_TYPE_UNSPECIFIED = 0,
  RESOURCE_TYPE_WATER = 1,
  RESOURCE_TYPE_ENERGY = 2,
  RESOURCE_TYPE_MONEY = 3,
  RESOURCE_TYPE_POPULATION = 4,
  RESOURCE_TYPE_CO2 = 5,
  ResourceType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ResourceType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ResourceType_IsValid(int value);
extern const uint32_t ResourceType_internal_data_[];
constexpr ResourceType ResourceType_MIN = static_cast<ResourceType>(0);
constexpr ResourceType ResourceType_MAX = static_cast<ResourceType>(5);
constexpr int ResourceType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
ResourceType_descriptor();
template <typename T>
const std::string& ResourceType_Name(T value) {
  static_assert(std::is_same<T, ResourceType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ResourceType_Name().");
  return ResourceType_Name(static_cast<ResourceType>(value));
}
template <>
inline const std::string& ResourceType_Name(ResourceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ResourceType_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool ResourceType_Parse(absl::string_view name, ResourceType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResourceType>(
      ResourceType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ResourceEffect final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game_api.v1.ResourceEffect) */ {
 public:
  inline ResourceEffect() : ResourceEffect(nullptr) {}
  ~ResourceEffect() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ResourceEffect(::google::protobuf::internal::ConstantInitialized);

  inline ResourceEffect(const ResourceEffect& from)
      : ResourceEffect(nullptr, from) {}
  ResourceEffect(ResourceEffect&& from) noexcept
    : ResourceEffect() {
    *this = ::std::move(from);
  }

  inline ResourceEffect& operator=(const ResourceEffect& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResourceEffect& operator=(ResourceEffect&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResourceEffect& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResourceEffect* internal_default_instance() {
    return reinterpret_cast<const ResourceEffect*>(
               &_ResourceEffect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResourceEffect& a, ResourceEffect& b) {
    a.Swap(&b);
  }
  inline void Swap(ResourceEffect* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResourceEffect* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResourceEffect* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResourceEffect>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResourceEffect& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ResourceEffect& from) {
    ResourceEffect::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ResourceEffect* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "game_api.v1.ResourceEffect";
  }
  protected:
  explicit ResourceEffect(::google::protobuf::Arena* arena);
  ResourceEffect(::google::protobuf::Arena* arena, const ResourceEffect& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResourceTypeFieldNumber = 1,
    kDeltaValueFieldNumber = 2,
  };
  // .game_api.v1.ResourceType resource_type = 1;
  void clear_resource_type() ;
  ::game_api::v1::ResourceType resource_type() const;
  void set_resource_type(::game_api::v1::ResourceType value);

  private:
  ::game_api::v1::ResourceType _internal_resource_type() const;
  void _internal_set_resource_type(::game_api::v1::ResourceType value);

  public:
  // int32 delta_value = 2;
  void clear_delta_value() ;
  ::int32_t delta_value() const;
  void set_delta_value(::int32_t value);

  private:
  ::int32_t _internal_delta_value() const;
  void _internal_set_delta_value(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.ResourceEffect)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    int resource_type_;
    ::int32_t delta_value_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};// -------------------------------------------------------------------

class PetitionResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game_api.v1.PetitionResponse) */ {
 public:
  inline PetitionResponse() : PetitionResponse(nullptr) {}
  ~PetitionResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PetitionResponse(::google::protobuf::internal::ConstantInitialized);

  inline PetitionResponse(const PetitionResponse& from)
      : PetitionResponse(nullptr, from) {}
  PetitionResponse(PetitionResponse&& from) noexcept
    : PetitionResponse() {
    *this = ::std::move(from);
  }

  inline PetitionResponse& operator=(const PetitionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PetitionResponse& operator=(PetitionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PetitionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PetitionResponse* internal_default_instance() {
    return reinterpret_cast<const PetitionResponse*>(
               &_PetitionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(PetitionResponse& a, PetitionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PetitionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PetitionResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PetitionResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PetitionResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PetitionResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PetitionResponse& from) {
    PetitionResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PetitionResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "game_api.v1.PetitionResponse";
  }
  protected:
  explicit PetitionResponse(::google::protobuf::Arena* arena);
  PetitionResponse(::google::protobuf::Arena* arena, const PetitionResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRespondedFieldNumber = 1,
    kAcceptedFieldNumber = 2,
  };
  // bool responded = 1;
  void clear_responded() ;
  bool responded() const;
  void set_responded(bool value);

  private:
  bool _internal_responded() const;
  void _internal_set_responded(bool value);

  public:
  // bool accepted = 2;
  void clear_accepted() ;
  bool accepted() const;
  void set_accepted(bool value);

  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.PetitionResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    bool responded_;
    bool accepted_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};// -------------------------------------------------------------------

class GameState_ResourcesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          GameState_ResourcesEntry_DoNotUse, ::int32_t, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      GameState_ResourcesEntry_DoNotUse, ::int32_t, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  GameState_ResourcesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameState_ResourcesEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit GameState_ResourcesEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const GameState_ResourcesEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const GameState_ResourcesEntry_DoNotUse*>(
        &_GameState_ResourcesEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_api_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class GameState_BuildingCountsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          GameState_BuildingCountsEntry_DoNotUse, ::int32_t, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      GameState_BuildingCountsEntry_DoNotUse, ::int32_t, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  GameState_BuildingCountsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameState_BuildingCountsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit GameState_BuildingCountsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const GameState_BuildingCountsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const GameState_BuildingCountsEntry_DoNotUse*>(
        &_GameState_BuildingCountsEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_api_5ftypes_2eproto;
};
// -------------------------------------------------------------------

class UIAction final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game_api.v1.UIAction) */ {
 public:
  inline UIAction() : UIAction(nullptr) {}
  ~UIAction() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UIAction(::google::protobuf::internal::ConstantInitialized);

  inline UIAction(const UIAction& from)
      : UIAction(nullptr, from) {}
  UIAction(UIAction&& from) noexcept
    : UIAction() {
    *this = ::std::move(from);
  }

  inline UIAction& operator=(const UIAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline UIAction& operator=(UIAction&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UIAction& default_instance() {
    return *internal_default_instance();
  }
  static inline const UIAction* internal_default_instance() {
    return reinterpret_cast<const UIAction*>(
               &_UIAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(UIAction& a, UIAction& b) {
    a.Swap(&b);
  }
  inline void Swap(UIAction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UIAction* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UIAction* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UIAction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UIAction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const UIAction& from) {
    UIAction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(UIAction* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "game_api.v1.UIAction";
  }
  protected:
  explicit UIAction(::google::protobuf::Arena* arena);
  UIAction(::google::protobuf::Arena* arena, const UIAction& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPetitionResponseFieldNumber = 1,
    kSaveGameFieldNumber = 2,
  };
  // .game_api.v1.PetitionResponse petition_response = 1;
  bool has_petition_response() const;
  void clear_petition_response() ;
  const ::game_api::v1::PetitionResponse& petition_response() const;
  PROTOBUF_NODISCARD ::game_api::v1::PetitionResponse* release_petition_response();
  ::game_api::v1::PetitionResponse* mutable_petition_response();
  void set_allocated_petition_response(::game_api::v1::PetitionResponse* value);
  void unsafe_arena_set_allocated_petition_response(::game_api::v1::PetitionResponse* value);
  ::game_api::v1::PetitionResponse* unsafe_arena_release_petition_response();

  private:
  const ::game_api::v1::PetitionResponse& _internal_petition_response() const;
  ::game_api::v1::PetitionResponse* _internal_mutable_petition_response();

  public:
  // bool save_game = 2;
  void clear_save_game() ;
  bool save_game() const;
  void set_save_game(bool value);

  private:
  bool _internal_save_game() const;
  void _internal_set_save_game(bool value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.UIAction)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::game_api::v1::PetitionResponse* petition_response_;
    bool save_game_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};// -------------------------------------------------------------------

class Building final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game_api.v1.Building) */ {
 public:
  inline Building() : Building(nullptr) {}
  ~Building() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Building(::google::protobuf::internal::ConstantInitialized);

  inline Building(const Building& from)
      : Building(nullptr, from) {}
  Building(Building&& from) noexcept
    : Building() {
    *this = ::std::move(from);
  }

  inline Building& operator=(const Building& from) {
    CopyFrom(from);
    return *this;
  }
  inline Building& operator=(Building&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Building& default_instance() {
    return *internal_default_instance();
  }
  static inline const Building* internal_default_instance() {
    return reinterpret_cast<const Building*>(
               &_Building_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Building& a, Building& b) {
    a.Swap(&b);
  }
  inline void Swap(Building* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Building* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Building* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Building>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Building& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Building& from) {
    Building::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Building* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "game_api.v1.Building";
  }
  protected:
  explicit Building(::google::protobuf::Arena* arena);
  Building(::google::protobuf::Arena* arena, const Building& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEffectsFieldNumber = 4,
    kTypeFieldNumber = 1,
    kBuildCostFieldNumber = 2,
    kTicksToCompleteFieldNumber = 3,
  };
  // repeated .game_api.v1.ResourceEffect effects = 4;
  int effects_size() const;
  private:
  int _internal_effects_size() const;

  public:
  void clear_effects() ;
  ::game_api::v1::ResourceEffect* mutable_effects(int index);
  ::google::protobuf::RepeatedPtrField< ::game_api::v1::ResourceEffect >*
      mutable_effects();
  private:
  const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>& _internal_effects() const;
  ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>* _internal_mutable_effects();
  public:
  const ::game_api::v1::ResourceEffect& effects(int index) const;
  ::game_api::v1::ResourceEffect* add_effects();
  const ::google::protobuf::RepeatedPtrField< ::game_api::v1::ResourceEffect >&
      effects() const;
  // .game_api.v1.BuildingType type = 1;
  void clear_type() ;
  ::game_api::v1::BuildingType type() const;
  void set_type(::game_api::v1::BuildingType value);

  private:
  ::game_api::v1::BuildingType _internal_type() const;
  void _internal_set_type(::game_api::v1::BuildingType value);

  public:
  // int32 build_cost = 2;
  void clear_build_cost() ;
  ::int32_t build_cost() const;
  void set_build_cost(::int32_t value);

  private:
  ::int32_t _internal_build_cost() const;
  void _internal_set_build_cost(::int32_t value);

  public:
  // int32 ticks_to_complete = 3;
  void clear_ticks_to_complete() ;
  ::int32_t ticks_to_complete() const;
  void set_ticks_to_complete(::int32_t value);

  private:
  ::int32_t _internal_ticks_to_complete() const;
  void _internal_set_ticks_to_complete(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.Building)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::game_api::v1::ResourceEffect > effects_;
    int type_;
    ::int32_t build_cost_;
    ::int32_t ticks_to_complete_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};// -------------------------------------------------------------------

class Petition final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game_api.v1.Petition) */ {
 public:
  inline Petition() : Petition(nullptr) {}
  ~Petition() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Petition(::google::protobuf::internal::ConstantInitialized);

  inline Petition(const Petition& from)
      : Petition(nullptr, from) {}
  Petition(Petition&& from) noexcept
    : Petition() {
    *this = ::std::move(from);
  }

  inline Petition& operator=(const Petition& from) {
    CopyFrom(from);
    return *this;
  }
  inline Petition& operator=(Petition&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Petition& default_instance() {
    return *internal_default_instance();
  }
  static inline const Petition* internal_default_instance() {
    return reinterpret_cast<const Petition*>(
               &_Petition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Petition& a, Petition& b) {
    a.Swap(&b);
  }
  inline void Swap(Petition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Petition* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Petition* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Petition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Petition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Petition& from) {
    Petition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Petition* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "game_api.v1.Petition";
  }
  protected:
  explicit Petition(::google::protobuf::Arena* arena);
  Petition(::google::protobuf::Arena* arena, const Petition& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBuildingFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // .game_api.v1.Building building = 2;
  bool has_building() const;
  void clear_building() ;
  const ::game_api::v1::Building& building() const;
  PROTOBUF_NODISCARD ::game_api::v1::Building* release_building();
  ::game_api::v1::Building* mutable_building();
  void set_allocated_building(::game_api::v1::Building* value);
  void unsafe_arena_set_allocated_building(::game_api::v1::Building* value);
  ::game_api::v1::Building* unsafe_arena_release_building();

  private:
  const ::game_api::v1::Building& _internal_building() const;
  ::game_api::v1::Building* _internal_mutable_building();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.Petition)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::game_api::v1::Building* building_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};// -------------------------------------------------------------------

class GameState final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game_api.v1.GameState) */ {
 public:
  inline GameState() : GameState(nullptr) {}
  ~GameState() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR GameState(::google::protobuf::internal::ConstantInitialized);

  inline GameState(const GameState& from)
      : GameState(nullptr, from) {}
  GameState(GameState&& from) noexcept
    : GameState() {
    *this = ::std::move(from);
  }

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameState& operator=(GameState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameState& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GameState& a, GameState& b) {
    a.Swap(&b);
  }
  inline void Swap(GameState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameState* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GameState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const GameState& from) {
    GameState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GameState* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "game_api.v1.GameState";
  }
  protected:
  explicit GameState(::google::protobuf::Arena* arena);
  GameState(::google::protobuf::Arena* arena, const GameState& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kBuildingCountsFieldNumber = 1,
    kResourcesFieldNumber = 5,
    kCurrentPetitionFieldNumber = 4,
  };
  // map<int32, int32> building_counts = 1;
  int building_counts_size() const;
  private:
  int _internal_building_counts_size() const;

  public:
  void clear_building_counts() ;
  const ::google::protobuf::Map<::int32_t, ::int32_t>& building_counts() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* mutable_building_counts();

  private:
  const ::google::protobuf::Map<::int32_t, ::int32_t>& _internal_building_counts() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* _internal_mutable_building_counts();

  public:
  // map<int32, int32> resources = 5;
  int resources_size() const;
  private:
  int _internal_resources_size() const;

  public:
  void clear_resources() ;
  const ::google::protobuf::Map<::int32_t, ::int32_t>& resources() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* mutable_resources();

  private:
  const ::google::protobuf::Map<::int32_t, ::int32_t>& _internal_resources() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* _internal_mutable_resources();

  public:
  // .game_api.v1.Petition current_petition = 4;
  bool has_current_petition() const;
  void clear_current_petition() ;
  const ::game_api::v1::Petition& current_petition() const;
  PROTOBUF_NODISCARD ::game_api::v1::Petition* release_current_petition();
  ::game_api::v1::Petition* mutable_current_petition();
  void set_allocated_current_petition(::game_api::v1::Petition* value);
  void unsafe_arena_set_allocated_current_petition(::game_api::v1::Petition* value);
  ::game_api::v1::Petition* unsafe_arena_release_current_petition();

  private:
  const ::game_api::v1::Petition& _internal_current_petition() const;
  ::game_api::v1::Petition* _internal_mutable_current_petition();

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.GameState)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 3,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<GameState_BuildingCountsEntry_DoNotUse, ::int32_t, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        building_counts_;
    ::google::protobuf::internal::MapField<GameState_ResourcesEntry_DoNotUse, ::int32_t, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        resources_;
    ::game_api::v1::Petition* current_petition_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ResourceEffect

// .game_api.v1.ResourceType resource_type = 1;
inline void ResourceEffect::clear_resource_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.resource_type_ = 0;
}
inline ::game_api::v1::ResourceType ResourceEffect::resource_type() const {
  // @@protoc_insertion_point(field_get:game_api.v1.ResourceEffect.resource_type)
  return _internal_resource_type();
}
inline void ResourceEffect::set_resource_type(::game_api::v1::ResourceType value) {
  _internal_set_resource_type(value);
  // @@protoc_insertion_point(field_set:game_api.v1.ResourceEffect.resource_type)
}
inline ::game_api::v1::ResourceType ResourceEffect::_internal_resource_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::game_api::v1::ResourceType>(_impl_.resource_type_);
}
inline void ResourceEffect::_internal_set_resource_type(::game_api::v1::ResourceType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.resource_type_ = value;
}

// int32 delta_value = 2;
inline void ResourceEffect::clear_delta_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.delta_value_ = 0;
}
inline ::int32_t ResourceEffect::delta_value() const {
  // @@protoc_insertion_point(field_get:game_api.v1.ResourceEffect.delta_value)
  return _internal_delta_value();
}
inline void ResourceEffect::set_delta_value(::int32_t value) {
  _internal_set_delta_value(value);
  // @@protoc_insertion_point(field_set:game_api.v1.ResourceEffect.delta_value)
}
inline ::int32_t ResourceEffect::_internal_delta_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.delta_value_;
}
inline void ResourceEffect::_internal_set_delta_value(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.delta_value_ = value;
}

// -------------------------------------------------------------------

// Building

// .game_api.v1.BuildingType type = 1;
inline void Building::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_ = 0;
}
inline ::game_api::v1::BuildingType Building::type() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.type)
  return _internal_type();
}
inline void Building::set_type(::game_api::v1::BuildingType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:game_api.v1.Building.type)
}
inline ::game_api::v1::BuildingType Building::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::game_api::v1::BuildingType>(_impl_.type_);
}
inline void Building::_internal_set_type(::game_api::v1::BuildingType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_ = value;
}

// int32 build_cost = 2;
inline void Building::clear_build_cost() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.build_cost_ = 0;
}
inline ::int32_t Building::build_cost() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.build_cost)
  return _internal_build_cost();
}
inline void Building::set_build_cost(::int32_t value) {
  _internal_set_build_cost(value);
  // @@protoc_insertion_point(field_set:game_api.v1.Building.build_cost)
}
inline ::int32_t Building::_internal_build_cost() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.build_cost_;
}
inline void Building::_internal_set_build_cost(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.build_cost_ = value;
}

// int32 ticks_to_complete = 3;
inline void Building::clear_ticks_to_complete() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.ticks_to_complete_ = 0;
}
inline ::int32_t Building::ticks_to_complete() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.ticks_to_complete)
  return _internal_ticks_to_complete();
}
inline void Building::set_ticks_to_complete(::int32_t value) {
  _internal_set_ticks_to_complete(value);
  // @@protoc_insertion_point(field_set:game_api.v1.Building.ticks_to_complete)
}
inline ::int32_t Building::_internal_ticks_to_complete() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.ticks_to_complete_;
}
inline void Building::_internal_set_ticks_to_complete(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.ticks_to_complete_ = value;
}

// repeated .game_api.v1.ResourceEffect effects = 4;
inline int Building::_internal_effects_size() const {
  return _internal_effects().size();
}
inline int Building::effects_size() const {
  return _internal_effects_size();
}
inline void Building::clear_effects() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.effects_.Clear();
}
inline ::game_api::v1::ResourceEffect* Building::mutable_effects(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:game_api.v1.Building.effects)
  return _internal_mutable_effects()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>* Building::mutable_effects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:game_api.v1.Building.effects)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_effects();
}
inline const ::game_api::v1::ResourceEffect& Building::effects(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.effects)
  return _internal_effects().Get(index);
}
inline ::game_api::v1::ResourceEffect* Building::add_effects() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::game_api::v1::ResourceEffect* _add = _internal_mutable_effects()->Add();
  // @@protoc_insertion_point(field_add:game_api.v1.Building.effects)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>& Building::effects() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:game_api.v1.Building.effects)
  return _internal_effects();
}
inline const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>&
Building::_internal_effects() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.effects_;
}
inline ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>*
Building::_internal_mutable_effects() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.effects_;
}

// -------------------------------------------------------------------

// Petition

// int32 id = 1;
inline void Petition::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_ = 0;
}
inline ::int32_t Petition::id() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Petition.id)
  return _internal_id();
}
inline void Petition::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:game_api.v1.Petition.id)
}
inline ::int32_t Petition::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_;
}
inline void Petition::_internal_set_id(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_ = value;
}

// .game_api.v1.Building building = 2;
inline bool Petition::has_building() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.building_ != nullptr);
  return value;
}
inline void Petition::clear_building() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.building_ != nullptr) _impl_.building_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::game_api::v1::Building& Petition::_internal_building() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::game_api::v1::Building* p = _impl_.building_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_api::v1::Building&>(::game_api::v1::_Building_default_instance_);
}
inline const ::game_api::v1::Building& Petition::building() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.Petition.building)
  return _internal_building();
}
inline void Petition::unsafe_arena_set_allocated_building(::game_api::v1::Building* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.building_);
  }
  _impl_.building_ = reinterpret_cast<::game_api::v1::Building*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_api.v1.Petition.building)
}
inline ::game_api::v1::Building* Petition::release_building() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::game_api::v1::Building* released = _impl_.building_;
  _impl_.building_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::game_api::v1::Building* Petition::unsafe_arena_release_building() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:game_api.v1.Petition.building)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::game_api::v1::Building* temp = _impl_.building_;
  _impl_.building_ = nullptr;
  return temp;
}
inline ::game_api::v1::Building* Petition::_internal_mutable_building() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.building_ == nullptr) {
    auto* p = CreateMaybeMessage<::game_api::v1::Building>(GetArena());
    _impl_.building_ = reinterpret_cast<::game_api::v1::Building*>(p);
  }
  return _impl_.building_;
}
inline ::game_api::v1::Building* Petition::mutable_building() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::game_api::v1::Building* _msg = _internal_mutable_building();
  // @@protoc_insertion_point(field_mutable:game_api.v1.Petition.building)
  return _msg;
}
inline void Petition::set_allocated_building(::game_api::v1::Building* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::game_api::v1::Building*>(_impl_.building_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::game_api::v1::Building*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.building_ = reinterpret_cast<::game_api::v1::Building*>(value);
  // @@protoc_insertion_point(field_set_allocated:game_api.v1.Petition.building)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GameState

// map<int32, int32> building_counts = 1;
inline int GameState::_internal_building_counts_size() const {
  return _internal_building_counts().size();
}
inline int GameState::building_counts_size() const {
  return _internal_building_counts_size();
}
inline void GameState::clear_building_counts() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.building_counts_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::_internal_building_counts() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.building_counts_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::building_counts() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:game_api.v1.GameState.building_counts)
  return _internal_building_counts();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* GameState::_internal_mutable_building_counts() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.building_counts_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* GameState::mutable_building_counts() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:game_api.v1.GameState.building_counts)
  return _internal_mutable_building_counts();
}

// map<int32, int32> resources = 5;
inline int GameState::_internal_resources_size() const {
  return _internal_resources().size();
}
inline int GameState::resources_size() const {
  return _internal_resources_size();
}
inline void GameState::clear_resources() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.resources_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::_internal_resources() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.resources_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::resources() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:game_api.v1.GameState.resources)
  return _internal_resources();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* GameState::_internal_mutable_resources() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.resources_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* GameState::mutable_resources() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:game_api.v1.GameState.resources)
  return _internal_mutable_resources();
}

// .game_api.v1.Petition current_petition = 4;
inline bool GameState::has_current_petition() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.current_petition_ != nullptr);
  return value;
}
inline void GameState::clear_current_petition() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.current_petition_ != nullptr) _impl_.current_petition_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::game_api::v1::Petition& GameState::_internal_current_petition() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::game_api::v1::Petition* p = _impl_.current_petition_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_api::v1::Petition&>(::game_api::v1::_Petition_default_instance_);
}
inline const ::game_api::v1::Petition& GameState::current_petition() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.GameState.current_petition)
  return _internal_current_petition();
}
inline void GameState::unsafe_arena_set_allocated_current_petition(::game_api::v1::Petition* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.current_petition_);
  }
  _impl_.current_petition_ = reinterpret_cast<::game_api::v1::Petition*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_api.v1.GameState.current_petition)
}
inline ::game_api::v1::Petition* GameState::release_current_petition() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::game_api::v1::Petition* released = _impl_.current_petition_;
  _impl_.current_petition_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::game_api::v1::Petition* GameState::unsafe_arena_release_current_petition() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:game_api.v1.GameState.current_petition)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::game_api::v1::Petition* temp = _impl_.current_petition_;
  _impl_.current_petition_ = nullptr;
  return temp;
}
inline ::game_api::v1::Petition* GameState::_internal_mutable_current_petition() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.current_petition_ == nullptr) {
    auto* p = CreateMaybeMessage<::game_api::v1::Petition>(GetArena());
    _impl_.current_petition_ = reinterpret_cast<::game_api::v1::Petition*>(p);
  }
  return _impl_.current_petition_;
}
inline ::game_api::v1::Petition* GameState::mutable_current_petition() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::game_api::v1::Petition* _msg = _internal_mutable_current_petition();
  // @@protoc_insertion_point(field_mutable:game_api.v1.GameState.current_petition)
  return _msg;
}
inline void GameState::set_allocated_current_petition(::game_api::v1::Petition* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::game_api::v1::Petition*>(_impl_.current_petition_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::game_api::v1::Petition*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.current_petition_ = reinterpret_cast<::game_api::v1::Petition*>(value);
  // @@protoc_insertion_point(field_set_allocated:game_api.v1.GameState.current_petition)
}

// -------------------------------------------------------------------

// PetitionResponse

// bool responded = 1;
inline void PetitionResponse::clear_responded() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.responded_ = false;
}
inline bool PetitionResponse::responded() const {
  // @@protoc_insertion_point(field_get:game_api.v1.PetitionResponse.responded)
  return _internal_responded();
}
inline void PetitionResponse::set_responded(bool value) {
  _internal_set_responded(value);
  // @@protoc_insertion_point(field_set:game_api.v1.PetitionResponse.responded)
}
inline bool PetitionResponse::_internal_responded() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.responded_;
}
inline void PetitionResponse::_internal_set_responded(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.responded_ = value;
}

// bool accepted = 2;
inline void PetitionResponse::clear_accepted() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.accepted_ = false;
}
inline bool PetitionResponse::accepted() const {
  // @@protoc_insertion_point(field_get:game_api.v1.PetitionResponse.accepted)
  return _internal_accepted();
}
inline void PetitionResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:game_api.v1.PetitionResponse.accepted)
}
inline bool PetitionResponse::_internal_accepted() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.accepted_;
}
inline void PetitionResponse::_internal_set_accepted(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.accepted_ = value;
}

// -------------------------------------------------------------------

// UIAction

// .game_api.v1.PetitionResponse petition_response = 1;
inline bool UIAction::has_petition_response() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.petition_response_ != nullptr);
  return value;
}
inline void UIAction::clear_petition_response() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.petition_response_ != nullptr) _impl_.petition_response_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::game_api::v1::PetitionResponse& UIAction::_internal_petition_response() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::game_api::v1::PetitionResponse* p = _impl_.petition_response_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_api::v1::PetitionResponse&>(::game_api::v1::_PetitionResponse_default_instance_);
}
inline const ::game_api::v1::PetitionResponse& UIAction::petition_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.UIAction.petition_response)
  return _internal_petition_response();
}
inline void UIAction::unsafe_arena_set_allocated_petition_response(::game_api::v1::PetitionResponse* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.petition_response_);
  }
  _impl_.petition_response_ = reinterpret_cast<::game_api::v1::PetitionResponse*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_api.v1.UIAction.petition_response)
}
inline ::game_api::v1::PetitionResponse* UIAction::release_petition_response() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::game_api::v1::PetitionResponse* released = _impl_.petition_response_;
  _impl_.petition_response_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::game_api::v1::PetitionResponse* UIAction::unsafe_arena_release_petition_response() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:game_api.v1.UIAction.petition_response)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::game_api::v1::PetitionResponse* temp = _impl_.petition_response_;
  _impl_.petition_response_ = nullptr;
  return temp;
}
inline ::game_api::v1::PetitionResponse* UIAction::_internal_mutable_petition_response() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.petition_response_ == nullptr) {
    auto* p = CreateMaybeMessage<::game_api::v1::PetitionResponse>(GetArena());
    _impl_.petition_response_ = reinterpret_cast<::game_api::v1::PetitionResponse*>(p);
  }
  return _impl_.petition_response_;
}
inline ::game_api::v1::PetitionResponse* UIAction::mutable_petition_response() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::game_api::v1::PetitionResponse* _msg = _internal_mutable_petition_response();
  // @@protoc_insertion_point(field_mutable:game_api.v1.UIAction.petition_response)
  return _msg;
}
inline void UIAction::set_allocated_petition_response(::game_api::v1::PetitionResponse* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::game_api::v1::PetitionResponse*>(_impl_.petition_response_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::game_api::v1::PetitionResponse*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.petition_response_ = reinterpret_cast<::game_api::v1::PetitionResponse*>(value);
  // @@protoc_insertion_point(field_set_allocated:game_api.v1.UIAction.petition_response)
}

// bool save_game = 2;
inline void UIAction::clear_save_game() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.save_game_ = false;
}
inline bool UIAction::save_game() const {
  // @@protoc_insertion_point(field_get:game_api.v1.UIAction.save_game)
  return _internal_save_game();
}
inline void UIAction::set_save_game(bool value) {
  _internal_set_save_game(value);
  // @@protoc_insertion_point(field_set:game_api.v1.UIAction.save_game)
}
inline bool UIAction::_internal_save_game() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.save_game_;
}
inline void UIAction::_internal_set_save_game(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.save_game_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace game_api


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::game_api::v1::BuildingType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::game_api::v1::BuildingType>() {
  return ::game_api::v1::BuildingType_descriptor();
}
template <>
struct is_proto_enum<::game_api::v1::ResourceType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::game_api::v1::ResourceType>() {
  return ::game_api::v1::ResourceType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_api_5ftypes_2eproto_2epb_2eh
