// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api_types.proto

#include "api_types.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace game_api {
namespace v1 {

inline constexpr ResourceEffect::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : resource_type_{static_cast< ::game_api::v1::ResourceType >(0)},
        delta_value_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResourceEffect::ResourceEffect(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResourceEffectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResourceEffectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResourceEffectDefaultTypeInternal() {}
  union {
    ResourceEffect _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResourceEffectDefaultTypeInternal _ResourceEffect_default_instance_;

inline constexpr PetitionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : responded_{false},
        accepted_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PetitionResponse::PetitionResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PetitionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PetitionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PetitionResponseDefaultTypeInternal() {}
  union {
    PetitionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PetitionResponseDefaultTypeInternal _PetitionResponse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR GameState_BuildingCountsEntry_DoNotUse::GameState_BuildingCountsEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    GameState_BuildingCountsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal _GameState_BuildingCountsEntry_DoNotUse_default_instance_;

inline constexpr UIAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        petition_response_{nullptr},
        save_game_{false} {}

template <typename>
PROTOBUF_CONSTEXPR UIAction::UIAction(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UIActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UIActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UIActionDefaultTypeInternal() {}
  union {
    UIAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UIActionDefaultTypeInternal _UIAction_default_instance_;

inline constexpr Building::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : effects_{},
        type_{static_cast< ::game_api::v1::BuildingType >(0)},
        build_cost_{0},
        ticks_to_complete_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Building::Building(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BuildingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildingDefaultTypeInternal() {}
  union {
    Building _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildingDefaultTypeInternal _Building_default_instance_;

inline constexpr Petition::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        building_{nullptr},
        id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Petition::Petition(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PetitionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PetitionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PetitionDefaultTypeInternal() {}
  union {
    Petition _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PetitionDefaultTypeInternal _Petition_default_instance_;

inline constexpr GameState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        building_counts_{},
        current_petition_{nullptr},
        resource_type_{static_cast< ::game_api::v1::ResourceType >(0)},
        resource_amount_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GameState::GameState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GameStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameStateDefaultTypeInternal() {}
  union {
    GameState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameStateDefaultTypeInternal _GameState_default_instance_;
}  // namespace v1
}  // namespace game_api
static ::_pb::Metadata file_level_metadata_api_5ftypes_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_api_5ftypes_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_5ftypes_2eproto = nullptr;
const ::uint32_t TableStruct_api_5ftypes_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::game_api::v1::ResourceEffect, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::ResourceEffect, _impl_.resource_type_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::ResourceEffect, _impl_.delta_value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.build_cost_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.ticks_to_complete_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Building, _impl_.effects_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::Petition, _impl_.building_),
    ~0u,
    0,
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse, value_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.building_counts_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.resource_type_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.resource_amount_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::GameState, _impl_.current_petition_),
    ~0u,
    ~0u,
    ~0u,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::game_api::v1::PetitionResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::PetitionResponse, _impl_.responded_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::PetitionResponse, _impl_.accepted_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _impl_.petition_response_),
    PROTOBUF_FIELD_OFFSET(::game_api::v1::UIAction, _impl_.save_game_),
    0,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::game_api::v1::ResourceEffect)},
        {10, -1, -1, sizeof(::game_api::v1::Building)},
        {22, 32, -1, sizeof(::game_api::v1::Petition)},
        {34, 44, -1, sizeof(::game_api::v1::GameState_BuildingCountsEntry_DoNotUse)},
        {46, 58, -1, sizeof(::game_api::v1::GameState)},
        {62, -1, -1, sizeof(::game_api::v1::PetitionResponse)},
        {72, 82, -1, sizeof(::game_api::v1::UIAction)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::game_api::v1::_ResourceEffect_default_instance_._instance,
    &::game_api::v1::_Building_default_instance_._instance,
    &::game_api::v1::_Petition_default_instance_._instance,
    &::game_api::v1::_GameState_BuildingCountsEntry_DoNotUse_default_instance_._instance,
    &::game_api::v1::_GameState_default_instance_._instance,
    &::game_api::v1::_PetitionResponse_default_instance_._instance,
    &::game_api::v1::_UIAction_default_instance_._instance,
};
const char descriptor_table_protodef_api_5ftypes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017api_types.proto\022\013game_api.v1\"W\n\016Resour"
    "ceEffect\0220\n\rresource_type\030\001 \001(\0162\031.game_a"
    "pi.v1.ResourceType\022\023\n\013delta_value\030\002 \001(\005\""
    "\220\001\n\010Building\022\'\n\004type\030\001 \001(\0162\031.game_api.v1"
    ".BuildingType\022\022\n\nbuild_cost\030\002 \001(\005\022\031\n\021tic"
    "ks_to_complete\030\003 \001(\005\022,\n\007effects\030\004 \003(\0132\033."
    "game_api.v1.ResourceEffect\"\?\n\010Petition\022\n"
    "\n\002id\030\001 \001(\005\022\'\n\010building\030\002 \001(\0132\025.game_api."
    "v1.Building\"\203\002\n\tGameState\022C\n\017building_co"
    "unts\030\001 \003(\0132*.game_api.v1.GameState.Build"
    "ingCountsEntry\0220\n\rresource_type\030\002 \001(\0162\031."
    "game_api.v1.ResourceType\022\027\n\017resource_amo"
    "unt\030\003 \001(\005\022/\n\020current_petition\030\004 \001(\0132\025.ga"
    "me_api.v1.Petition\0325\n\023BuildingCountsEntr"
    "y\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\"7\n\020Pet"
    "itionResponse\022\021\n\tresponded\030\001 \001(\010\022\020\n\010acce"
    "pted\030\002 \001(\010\"W\n\010UIAction\0228\n\021petition_respo"
    "nse\030\001 \001(\0132\035.game_api.v1.PetitionResponse"
    "\022\021\n\tsave_game\030\002 \001(\010*\366\003\n\014BuildingType\022\035\n\031"
    "BUILDING_TYPE_UNSPECIFIED\020\000\022\035\n\031BUILDING_"
    "TYPE_POWER_PLANT\020\001\022\'\n#BUILDING_TYPE_WATE"
    "R_TREATMENT_PLANT\020\002\022\"\n\036BUILDING_TYPE_SOL"
    "AR_PANEL_FARM\020\003\022&\n\"BUILDING_TYPE_SOLAR_P"
    "ANEL_ROOFTOPS\020\004\022*\n&BUILDING_TYPE_PUBLIC_"
    "TRANSPORT_UPGRADE\020\005\022#\n\037BUILDING_TYPE_WIN"
    "D_TURBINE_FARM\020\006\022%\n!BUILDING_TYPE_HYDROE"
    "LECTRIC_PLANT\020\007\022 \n\034BUILDING_TYPE_URBAN_G"
    "REENING\020\010\022-\n)BUILDING_TYPE_WATER_SAVING_"
    "INFRASTRUCTURE\020\t\022!\n\035BUILDING_TYPE_INDUST"
    "RIAL_ZONE\020\n\022#\n\037BUILDING_TYPE_AIRPORT_EXP"
    "ANSION\020\013\022\"\n\036BUILDING_TYPE_ROAD_IMPROVEME"
    "NT\020\014*\256\001\n\014ResourceType\022\035\n\031RESOURCE_TYPE_U"
    "NSPECIFIED\020\000\022\027\n\023RESOURCE_TYPE_WATER\020\001\022\030\n"
    "\024RESOURCE_TYPE_ENERGY\020\002\022\027\n\023RESOURCE_TYPE"
    "_MONEY\020\003\022\034\n\030RESOURCE_TYPE_POPULATION\020\004\022\025"
    "\n\021RESOURCE_TYPE_CO2\020\005b\006proto3"
};
static ::absl::once_flag descriptor_table_api_5ftypes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_api_5ftypes_2eproto = {
    false,
    false,
    1429,
    descriptor_table_protodef_api_5ftypes_2eproto,
    "api_types.proto",
    &descriptor_table_api_5ftypes_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_api_5ftypes_2eproto::offsets,
    file_level_metadata_api_5ftypes_2eproto,
    file_level_enum_descriptors_api_5ftypes_2eproto,
    file_level_service_descriptors_api_5ftypes_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_api_5ftypes_2eproto_getter() {
  return &descriptor_table_api_5ftypes_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_api_5ftypes_2eproto(&descriptor_table_api_5ftypes_2eproto);
namespace game_api {
namespace v1 {
const ::google::protobuf::EnumDescriptor* BuildingType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_api_5ftypes_2eproto);
  return file_level_enum_descriptors_api_5ftypes_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t BuildingType_internal_data_[] = {
    851968u, 0u, };
bool BuildingType_IsValid(int value) {
  return 0 <= value && value <= 12;
}
const ::google::protobuf::EnumDescriptor* ResourceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_api_5ftypes_2eproto);
  return file_level_enum_descriptors_api_5ftypes_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ResourceType_internal_data_[] = {
    393216u, 0u, };
bool ResourceType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// ===================================================================

class ResourceEffect::_Internal {
 public:
};

ResourceEffect::ResourceEffect(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.ResourceEffect)
}
ResourceEffect::ResourceEffect(
    ::google::protobuf::Arena* arena, const ResourceEffect& from)
    : ResourceEffect(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ResourceEffect::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ResourceEffect::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, resource_type_),
           0,
           offsetof(Impl_, delta_value_) -
               offsetof(Impl_, resource_type_) +
               sizeof(Impl_::delta_value_));
}
ResourceEffect::~ResourceEffect() {
  // @@protoc_insertion_point(destructor:game_api.v1.ResourceEffect)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ResourceEffect::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ResourceEffect::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.ResourceEffect)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.resource_type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.delta_value_) -
      reinterpret_cast<char*>(&_impl_.resource_type_)) + sizeof(_impl_.delta_value_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ResourceEffect::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ResourceEffect::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ResourceEffect_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 delta_value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResourceEffect, _impl_.delta_value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.delta_value_)}},
    // .game_api.v1.ResourceType resource_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResourceEffect, _impl_.resource_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.resource_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .game_api.v1.ResourceType resource_type = 1;
    {PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.resource_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 delta_value = 2;
    {PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.delta_value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ResourceEffect::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.ResourceEffect)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .game_api.v1.ResourceType resource_type = 1;
  if (this->_internal_resource_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_resource_type(), target);
  }

  // int32 delta_value = 2;
  if (this->_internal_delta_value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_delta_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.ResourceEffect)
  return target;
}

::size_t ResourceEffect::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.ResourceEffect)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_api.v1.ResourceType resource_type = 1;
  if (this->_internal_resource_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_resource_type());
  }

  // int32 delta_value = 2;
  if (this->_internal_delta_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_delta_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ResourceEffect::_class_data_ = {
    ResourceEffect::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ResourceEffect::GetClassData() const {
  return &_class_data_;
}

void ResourceEffect::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ResourceEffect*>(&to_msg);
  auto& from = static_cast<const ResourceEffect&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.ResourceEffect)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_resource_type() != 0) {
    _this->_internal_set_resource_type(from._internal_resource_type());
  }
  if (from._internal_delta_value() != 0) {
    _this->_internal_set_delta_value(from._internal_delta_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResourceEffect::CopyFrom(const ResourceEffect& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.ResourceEffect)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ResourceEffect::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ResourceEffect::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ResourceEffect::InternalSwap(ResourceEffect* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.delta_value_)
      + sizeof(ResourceEffect::_impl_.delta_value_)
      - PROTOBUF_FIELD_OFFSET(ResourceEffect, _impl_.resource_type_)>(
          reinterpret_cast<char*>(&_impl_.resource_type_),
          reinterpret_cast<char*>(&other->_impl_.resource_type_));
}

::google::protobuf::Metadata ResourceEffect::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[0]);
}
// ===================================================================

class Building::_Internal {
 public:
};

Building::Building(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.Building)
}
inline PROTOBUF_NDEBUG_INLINE Building::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : effects_{visibility, arena, from.effects_},
        _cached_size_{0} {}

Building::Building(
    ::google::protobuf::Arena* arena,
    const Building& from)
    : ::google::protobuf::Message(arena) {
  Building* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, ticks_to_complete_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::ticks_to_complete_));

  // @@protoc_insertion_point(copy_constructor:game_api.v1.Building)
}
inline PROTOBUF_NDEBUG_INLINE Building::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : effects_{visibility, arena},
        _cached_size_{0} {}

inline void Building::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, ticks_to_complete_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::ticks_to_complete_));
}
Building::~Building() {
  // @@protoc_insertion_point(destructor:game_api.v1.Building)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Building::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Building::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.Building)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.effects_.Clear();
  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.ticks_to_complete_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.ticks_to_complete_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Building::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> Building::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Building_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .game_api.v1.ResourceEffect effects = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.effects_)}},
    // .game_api.v1.BuildingType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Building, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.type_)}},
    // int32 build_cost = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Building, _impl_.build_cost_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.build_cost_)}},
    // int32 ticks_to_complete = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Building, _impl_.ticks_to_complete_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.ticks_to_complete_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .game_api.v1.BuildingType type = 1;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 build_cost = 2;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.build_cost_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 ticks_to_complete = 3;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.ticks_to_complete_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .game_api.v1.ResourceEffect effects = 4;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.effects_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game_api::v1::ResourceEffect>()},
  }}, {{
  }},
};

::uint8_t* Building::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.Building)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .game_api.v1.BuildingType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  // int32 build_cost = 2;
  if (this->_internal_build_cost() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_build_cost(), target);
  }

  // int32 ticks_to_complete = 3;
  if (this->_internal_ticks_to_complete() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_ticks_to_complete(), target);
  }

  // repeated .game_api.v1.ResourceEffect effects = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_effects_size()); i < n; i++) {
    const auto& repfield = this->_internal_effects().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.Building)
  return target;
}

::size_t Building::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.Building)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .game_api.v1.ResourceEffect effects = 4;
  total_size += 1UL * this->_internal_effects_size();
  for (const auto& msg : this->_internal_effects()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // .game_api.v1.BuildingType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // int32 build_cost = 2;
  if (this->_internal_build_cost() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_build_cost());
  }

  // int32 ticks_to_complete = 3;
  if (this->_internal_ticks_to_complete() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_ticks_to_complete());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Building::_class_data_ = {
    Building::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Building::GetClassData() const {
  return &_class_data_;
}

void Building::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Building*>(&to_msg);
  auto& from = static_cast<const Building&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.Building)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_effects()->MergeFrom(
      from._internal_effects());
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_build_cost() != 0) {
    _this->_internal_set_build_cost(from._internal_build_cost());
  }
  if (from._internal_ticks_to_complete() != 0) {
    _this->_internal_set_ticks_to_complete(from._internal_ticks_to_complete());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Building::CopyFrom(const Building& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.Building)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Building::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Building::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Building::InternalSwap(Building* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.effects_.InternalSwap(&other->_impl_.effects_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Building, _impl_.ticks_to_complete_)
      + sizeof(Building::_impl_.ticks_to_complete_)
      - PROTOBUF_FIELD_OFFSET(Building, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata Building::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[1]);
}
// ===================================================================

class Petition::_Internal {
 public:
  using HasBits = decltype(std::declval<Petition>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Petition, _impl_._has_bits_);
  static const ::game_api::v1::Building& building(const Petition* msg);
  static void set_has_building(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::game_api::v1::Building& Petition::_Internal::building(const Petition* msg) {
  return *msg->_impl_.building_;
}
Petition::Petition(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.Petition)
}
inline PROTOBUF_NDEBUG_INLINE Petition::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Petition::Petition(
    ::google::protobuf::Arena* arena,
    const Petition& from)
    : ::google::protobuf::Message(arena) {
  Petition* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.building_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::game_api::v1::Building>(arena, *from._impl_.building_)
                : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:game_api.v1.Petition)
}
inline PROTOBUF_NDEBUG_INLINE Petition::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Petition::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, building_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, building_) +
               sizeof(Impl_::id_));
}
Petition::~Petition() {
  // @@protoc_insertion_point(destructor:game_api.v1.Petition)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Petition::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.building_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Petition::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.Petition)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.building_ != nullptr);
    _impl_.building_->Clear();
  }
  _impl_.id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Petition::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> Petition::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Petition, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Petition_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .game_api.v1.Building building = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Petition, _impl_.building_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Petition, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Petition, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Petition, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .game_api.v1.Building building = 2;
    {PROTOBUF_FIELD_OFFSET(Petition, _impl_.building_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game_api::v1::Building>()},
  }}, {{
  }},
};

::uint8_t* Petition::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.Petition)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .game_api.v1.Building building = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::building(this),
        _Internal::building(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.Petition)
  return target;
}

::size_t Petition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.Petition)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_api.v1.Building building = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.building_);
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Petition::_class_data_ = {
    Petition::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Petition::GetClassData() const {
  return &_class_data_;
}

void Petition::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Petition*>(&to_msg);
  auto& from = static_cast<const Petition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.Petition)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_building()->::game_api::v1::Building::MergeFrom(
        from._internal_building());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Petition::CopyFrom(const Petition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.Petition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Petition::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Petition::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Petition::InternalSwap(Petition* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Petition, _impl_.id_)
      + sizeof(Petition::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Petition, _impl_.building_)>(
          reinterpret_cast<char*>(&_impl_.building_),
          reinterpret_cast<char*>(&other->_impl_.building_));
}

::google::protobuf::Metadata Petition::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[2]);
}
// ===================================================================

GameState_BuildingCountsEntry_DoNotUse::GameState_BuildingCountsEntry_DoNotUse() {}
GameState_BuildingCountsEntry_DoNotUse::GameState_BuildingCountsEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata GameState_BuildingCountsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[3]);
}
// ===================================================================

class GameState::_Internal {
 public:
  using HasBits = decltype(std::declval<GameState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(GameState, _impl_._has_bits_);
  static const ::game_api::v1::Petition& current_petition(const GameState* msg);
  static void set_has_current_petition(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::game_api::v1::Petition& GameState::_Internal::current_petition(const GameState* msg) {
  return *msg->_impl_.current_petition_;
}
GameState::GameState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.GameState)
}
inline PROTOBUF_NDEBUG_INLINE GameState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        building_counts_{visibility, arena, from.building_counts_} {}

GameState::GameState(
    ::google::protobuf::Arena* arena,
    const GameState& from)
    : ::google::protobuf::Message(arena) {
  GameState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.current_petition_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::game_api::v1::Petition>(arena, *from._impl_.current_petition_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, resource_type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, resource_type_),
           offsetof(Impl_, resource_amount_) -
               offsetof(Impl_, resource_type_) +
               sizeof(Impl_::resource_amount_));

  // @@protoc_insertion_point(copy_constructor:game_api.v1.GameState)
}
inline PROTOBUF_NDEBUG_INLINE GameState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        building_counts_{visibility, arena} {}

inline void GameState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, current_petition_),
           0,
           offsetof(Impl_, resource_amount_) -
               offsetof(Impl_, current_petition_) +
               sizeof(Impl_::resource_amount_));
}
GameState::~GameState() {
  // @@protoc_insertion_point(destructor:game_api.v1.GameState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GameState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.current_petition_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GameState::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.GameState)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.building_counts_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.current_petition_ != nullptr);
    _impl_.current_petition_->Clear();
  }
  ::memset(&_impl_.resource_type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.resource_amount_) -
      reinterpret_cast<char*>(&_impl_.resource_type_)) + sizeof(_impl_.resource_amount_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GameState::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 0, 2> GameState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GameState, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GameState_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .game_api.v1.Petition current_petition = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 1, PROTOBUF_FIELD_OFFSET(GameState, _impl_.current_petition_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // .game_api.v1.ResourceType resource_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameState, _impl_.resource_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GameState, _impl_.resource_type_)}},
    // int32 resource_amount = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GameState, _impl_.resource_amount_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GameState, _impl_.resource_amount_)}},
  }}, {{
    65535, 65535
  }}, {{
    // map<int32, int32> building_counts = 1;
    {PROTOBUF_FIELD_OFFSET(GameState, _impl_.building_counts_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // .game_api.v1.ResourceType resource_type = 2;
    {PROTOBUF_FIELD_OFFSET(GameState, _impl_.resource_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 resource_amount = 3;
    {PROTOBUF_FIELD_OFFSET(GameState, _impl_.resource_amount_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .game_api.v1.Petition current_petition = 4;
    {PROTOBUF_FIELD_OFFSET(GameState, _impl_.current_petition_), _Internal::kHasBitsOffset + 0, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(GameState()._impl_.building_counts_)>(
        1, 0, 0, 5,
        5)},
    {::_pbi::TcParser::GetTable<::game_api::v1::Petition>()},
  }}, {{
  }},
};

::uint8_t* GameState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.GameState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<int32, int32> building_counts = 1;
  if (!_internal_building_counts().empty()) {
    using MapType = ::google::protobuf::Map<::int32_t, ::int32_t>;
    using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::int32_t,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_INT32>;
    const auto& field = _internal_building_counts();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  // .game_api.v1.ResourceType resource_type = 2;
  if (this->_internal_resource_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_resource_type(), target);
  }

  // int32 resource_amount = 3;
  if (this->_internal_resource_amount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_resource_amount(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .game_api.v1.Petition current_petition = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::current_petition(this),
        _Internal::current_petition(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.GameState)
  return target;
}

::size_t GameState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.GameState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, int32> building_counts = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_building_counts_size());
  for (const auto& entry : _internal_building_counts()) {
    total_size += _pbi::MapEntryFuncs<::int32_t, ::int32_t,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
  }
  // .game_api.v1.Petition current_petition = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.current_petition_);
  }

  // .game_api.v1.ResourceType resource_type = 2;
  if (this->_internal_resource_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_resource_type());
  }

  // int32 resource_amount = 3;
  if (this->_internal_resource_amount() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_resource_amount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GameState::_class_data_ = {
    GameState::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GameState::GetClassData() const {
  return &_class_data_;
}

void GameState::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GameState*>(&to_msg);
  auto& from = static_cast<const GameState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.GameState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.building_counts_.MergeFrom(from._impl_.building_counts_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_current_petition()->::game_api::v1::Petition::MergeFrom(
        from._internal_current_petition());
  }
  if (from._internal_resource_type() != 0) {
    _this->_internal_set_resource_type(from._internal_resource_type());
  }
  if (from._internal_resource_amount() != 0) {
    _this->_internal_set_resource_amount(from._internal_resource_amount());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GameState::CopyFrom(const GameState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.GameState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GameState::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GameState::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GameState::InternalSwap(GameState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.building_counts_.InternalSwap(&other->_impl_.building_counts_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameState, _impl_.resource_amount_)
      + sizeof(GameState::_impl_.resource_amount_)
      - PROTOBUF_FIELD_OFFSET(GameState, _impl_.current_petition_)>(
          reinterpret_cast<char*>(&_impl_.current_petition_),
          reinterpret_cast<char*>(&other->_impl_.current_petition_));
}

::google::protobuf::Metadata GameState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[4]);
}
// ===================================================================

class PetitionResponse::_Internal {
 public:
};

PetitionResponse::PetitionResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.PetitionResponse)
}
PetitionResponse::PetitionResponse(
    ::google::protobuf::Arena* arena, const PetitionResponse& from)
    : PetitionResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PetitionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PetitionResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, responded_),
           0,
           offsetof(Impl_, accepted_) -
               offsetof(Impl_, responded_) +
               sizeof(Impl_::accepted_));
}
PetitionResponse::~PetitionResponse() {
  // @@protoc_insertion_point(destructor:game_api.v1.PetitionResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PetitionResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PetitionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.PetitionResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.responded_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.accepted_) -
      reinterpret_cast<char*>(&_impl_.responded_)) + sizeof(_impl_.accepted_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PetitionResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> PetitionResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PetitionResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool accepted = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PetitionResponse, _impl_.accepted_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.accepted_)}},
    // bool responded = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PetitionResponse, _impl_.responded_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.responded_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool responded = 1;
    {PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.responded_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool accepted = 2;
    {PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.accepted_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* PetitionResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.PetitionResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool responded = 1;
  if (this->_internal_responded() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_responded(), target);
  }

  // bool accepted = 2;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_accepted(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.PetitionResponse)
  return target;
}

::size_t PetitionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.PetitionResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool responded = 1;
  if (this->_internal_responded() != 0) {
    total_size += 2;
  }

  // bool accepted = 2;
  if (this->_internal_accepted() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PetitionResponse::_class_data_ = {
    PetitionResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PetitionResponse::GetClassData() const {
  return &_class_data_;
}

void PetitionResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PetitionResponse*>(&to_msg);
  auto& from = static_cast<const PetitionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.PetitionResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_responded() != 0) {
    _this->_internal_set_responded(from._internal_responded());
  }
  if (from._internal_accepted() != 0) {
    _this->_internal_set_accepted(from._internal_accepted());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PetitionResponse::CopyFrom(const PetitionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.PetitionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PetitionResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PetitionResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PetitionResponse::InternalSwap(PetitionResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.accepted_)
      + sizeof(PetitionResponse::_impl_.accepted_)
      - PROTOBUF_FIELD_OFFSET(PetitionResponse, _impl_.responded_)>(
          reinterpret_cast<char*>(&_impl_.responded_),
          reinterpret_cast<char*>(&other->_impl_.responded_));
}

::google::protobuf::Metadata PetitionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[5]);
}
// ===================================================================

class UIAction::_Internal {
 public:
  using HasBits = decltype(std::declval<UIAction>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(UIAction, _impl_._has_bits_);
  static const ::game_api::v1::PetitionResponse& petition_response(const UIAction* msg);
  static void set_has_petition_response(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::game_api::v1::PetitionResponse& UIAction::_Internal::petition_response(const UIAction* msg) {
  return *msg->_impl_.petition_response_;
}
UIAction::UIAction(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game_api.v1.UIAction)
}
inline PROTOBUF_NDEBUG_INLINE UIAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

UIAction::UIAction(
    ::google::protobuf::Arena* arena,
    const UIAction& from)
    : ::google::protobuf::Message(arena) {
  UIAction* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.petition_response_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::game_api::v1::PetitionResponse>(arena, *from._impl_.petition_response_)
                : nullptr;
  _impl_.save_game_ = from._impl_.save_game_;

  // @@protoc_insertion_point(copy_constructor:game_api.v1.UIAction)
}
inline PROTOBUF_NDEBUG_INLINE UIAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UIAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, petition_response_),
           0,
           offsetof(Impl_, save_game_) -
               offsetof(Impl_, petition_response_) +
               sizeof(Impl_::save_game_));
}
UIAction::~UIAction() {
  // @@protoc_insertion_point(destructor:game_api.v1.UIAction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UIAction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.petition_response_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UIAction::Clear() {
// @@protoc_insertion_point(message_clear_start:game_api.v1.UIAction)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.petition_response_ != nullptr);
    _impl_.petition_response_->Clear();
  }
  _impl_.save_game_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UIAction::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> UIAction::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UIAction, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_UIAction_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool save_game = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UIAction, _impl_.save_game_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UIAction, _impl_.save_game_)}},
    // .game_api.v1.PetitionResponse petition_response = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(UIAction, _impl_.petition_response_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .game_api.v1.PetitionResponse petition_response = 1;
    {PROTOBUF_FIELD_OFFSET(UIAction, _impl_.petition_response_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool save_game = 2;
    {PROTOBUF_FIELD_OFFSET(UIAction, _impl_.save_game_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game_api::v1::PetitionResponse>()},
  }}, {{
  }},
};

::uint8_t* UIAction::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_api.v1.UIAction)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .game_api.v1.PetitionResponse petition_response = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::petition_response(this),
        _Internal::petition_response(this).GetCachedSize(), target, stream);
  }

  // bool save_game = 2;
  if (this->_internal_save_game() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_save_game(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_api.v1.UIAction)
  return target;
}

::size_t UIAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_api.v1.UIAction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_api.v1.PetitionResponse petition_response = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.petition_response_);
  }

  // bool save_game = 2;
  if (this->_internal_save_game() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UIAction::_class_data_ = {
    UIAction::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UIAction::GetClassData() const {
  return &_class_data_;
}

void UIAction::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UIAction*>(&to_msg);
  auto& from = static_cast<const UIAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_api.v1.UIAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_petition_response()->::game_api::v1::PetitionResponse::MergeFrom(
        from._internal_petition_response());
  }
  if (from._internal_save_game() != 0) {
    _this->_internal_set_save_game(from._internal_save_game());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UIAction::CopyFrom(const UIAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_api.v1.UIAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UIAction::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UIAction::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UIAction::InternalSwap(UIAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UIAction, _impl_.save_game_)
      + sizeof(UIAction::_impl_.save_game_)
      - PROTOBUF_FIELD_OFFSET(UIAction, _impl_.petition_response_)>(
          reinterpret_cast<char*>(&_impl_.petition_response_),
          reinterpret_cast<char*>(&other->_impl_.petition_response_));
}

::google::protobuf::Metadata UIAction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_api_5ftypes_2eproto_getter, &descriptor_table_api_5ftypes_2eproto_once,
      file_level_metadata_api_5ftypes_2eproto[6]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace game_api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
