// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api_types.proto
// Protobuf C++ Version: 6.33.4

#ifndef api_5ftypes_2eproto_2epb_2eh
#define api_5ftypes_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_5ftypes_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_5ftypes_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_api_5ftypes_2eproto;
}  // extern "C"
namespace game_api {
namespace v1 {
enum BuildingType : int;
extern const uint32_t BuildingType_internal_data_[];
enum ResourceType : int;
extern const uint32_t ResourceType_internal_data_[];
class Building;
struct BuildingDefaultTypeInternal;
extern BuildingDefaultTypeInternal _Building_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Building_class_data_;
class GameState;
struct GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GameState_class_data_;
class GameState_BuildingCountsEntry_DoNotUse;
struct GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal;
extern GameState_BuildingCountsEntry_DoNotUseDefaultTypeInternal _GameState_BuildingCountsEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GameState_BuildingCountsEntry_DoNotUse_class_data_;
class GameState_ResourcesEntry_DoNotUse;
struct GameState_ResourcesEntry_DoNotUseDefaultTypeInternal;
extern GameState_ResourcesEntry_DoNotUseDefaultTypeInternal _GameState_ResourcesEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GameState_ResourcesEntry_DoNotUse_class_data_;
class Petition;
struct PetitionDefaultTypeInternal;
extern PetitionDefaultTypeInternal _Petition_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Petition_class_data_;
class PetitionResponse;
struct PetitionResponseDefaultTypeInternal;
extern PetitionResponseDefaultTypeInternal _PetitionResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PetitionResponse_class_data_;
class ResourceEffect;
struct ResourceEffectDefaultTypeInternal;
extern ResourceEffectDefaultTypeInternal _ResourceEffect_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ResourceEffect_class_data_;
class UIAction;
struct UIActionDefaultTypeInternal;
extern UIActionDefaultTypeInternal _UIAction_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UIAction_class_data_;
}  // namespace v1
}  // namespace game_api
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::game_api::v1::BuildingType_internal_data_>
    internal::EnumTraitsImpl::value<::game_api::v1::BuildingType>;
template <>
internal::EnumTraitsT<::game_api::v1::ResourceType_internal_data_>
    internal::EnumTraitsImpl::value<::game_api::v1::ResourceType>;
}  // namespace protobuf
}  // namespace google

namespace game_api {
namespace v1 {
enum BuildingType : int {
  BUILDING_TYPE_UNSPECIFIED = 0,
  BUILDING_TYPE_POWER_PLANT = 1,
  BUILDING_TYPE_WATER_TREATMENT_PLANT = 2,
  BUILDING_TYPE_SOLAR_PANEL_FARM = 3,
  BUILDING_TYPE_SOLAR_PANEL_ROOFTOPS = 4,
  BUILDING_TYPE_PUBLIC_TRANSPORT_UPGRADE = 5,
  BUILDING_TYPE_WIND_TURBINE_FARM = 6,
  BUILDING_TYPE_HYDROELECTRIC_PLANT = 7,
  BUILDING_TYPE_URBAN_GREENING = 8,
  BUILDING_TYPE_WATER_SAVING_INFRASTRUCTURE = 9,
  BUILDING_TYPE_INDUSTRIAL_ZONE = 10,
  BUILDING_TYPE_AIRPORT_EXPANSION = 11,
  BUILDING_TYPE_ROAD_IMPROVEMENT = 12,
  BuildingType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  BuildingType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t BuildingType_internal_data_[];
inline constexpr BuildingType BuildingType_MIN =
    static_cast<BuildingType>(0);
inline constexpr BuildingType BuildingType_MAX =
    static_cast<BuildingType>(12);
inline bool BuildingType_IsValid(int value) {
  return 0 <= value && value <= 12;
}
inline constexpr int BuildingType_ARRAYSIZE = 12 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL BuildingType_descriptor();
template <typename T>
const ::std::string& BuildingType_Name(T value) {
  static_assert(::std::is_same<T, BuildingType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to BuildingType_Name().");
  return BuildingType_Name(static_cast<BuildingType>(value));
}
template <>
inline const ::std::string& BuildingType_Name(BuildingType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<BuildingType_descriptor, 0, 12>(
      static_cast<int>(value));
}
inline bool BuildingType_Parse(
    ::absl::string_view name, BuildingType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<BuildingType>(BuildingType_descriptor(), name,
                                           value);
}
enum ResourceType : int {
  RESOURCE_TYPE_UNSPECIFIED = 0,
  RESOURCE_TYPE_WATER = 1,
  RESOURCE_TYPE_ENERGY = 2,
  RESOURCE_TYPE_MONEY = 3,
  RESOURCE_TYPE_POPULATION = 4,
  RESOURCE_TYPE_CO2 = 5,
  ResourceType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ResourceType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ResourceType_internal_data_[];
inline constexpr ResourceType ResourceType_MIN =
    static_cast<ResourceType>(0);
inline constexpr ResourceType ResourceType_MAX =
    static_cast<ResourceType>(5);
inline bool ResourceType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int ResourceType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResourceType_descriptor();
template <typename T>
const ::std::string& ResourceType_Name(T value) {
  static_assert(::std::is_same<T, ResourceType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ResourceType_Name().");
  return ResourceType_Name(static_cast<ResourceType>(value));
}
template <>
inline const ::std::string& ResourceType_Name(ResourceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ResourceType_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool ResourceType_Parse(
    ::absl::string_view name, ResourceType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResourceType>(ResourceType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class ResourceEffect final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game_api.v1.ResourceEffect) */ {
 public:
  inline ResourceEffect() : ResourceEffect(nullptr) {}
  ~ResourceEffect() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResourceEffect* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResourceEffect));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResourceEffect(::google::protobuf::internal::ConstantInitialized);

  inline ResourceEffect(const ResourceEffect& from) : ResourceEffect(nullptr, from) {}
  inline ResourceEffect(ResourceEffect&& from) noexcept
      : ResourceEffect(nullptr, ::std::move(from)) {}
  inline ResourceEffect& operator=(const ResourceEffect& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResourceEffect& operator=(ResourceEffect&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResourceEffect& default_instance() {
    return *reinterpret_cast<const ResourceEffect*>(
        &_ResourceEffect_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ResourceEffect& a, ResourceEffect& b) { a.Swap(&b); }
  inline void Swap(ResourceEffect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResourceEffect* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResourceEffect* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResourceEffect>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResourceEffect& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResourceEffect& from) { ResourceEffect::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResourceEffect* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game_api.v1.ResourceEffect"; }

  explicit ResourceEffect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ResourceEffect(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ResourceEffect& from);
  ResourceEffect(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ResourceEffect&& from) noexcept
      : ResourceEffect(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResourceTypeFieldNumber = 1,
    kDeltaValueFieldNumber = 2,
  };
  // .game_api.v1.ResourceType resource_type = 1;
  void clear_resource_type() ;
  ::game_api::v1::ResourceType resource_type() const;
  void set_resource_type(::game_api::v1::ResourceType value);

  private:
  ::game_api::v1::ResourceType _internal_resource_type() const;
  void _internal_set_resource_type(::game_api::v1::ResourceType value);

  public:
  // int32 delta_value = 2;
  void clear_delta_value() ;
  ::int32_t delta_value() const;
  void set_delta_value(::int32_t value);

  private:
  ::int32_t _internal_delta_value() const;
  void _internal_set_delta_value(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.ResourceEffect)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ResourceEffect& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int resource_type_;
    ::int32_t delta_value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ResourceEffect_class_data_;
// -------------------------------------------------------------------

class PetitionResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game_api.v1.PetitionResponse) */ {
 public:
  inline PetitionResponse() : PetitionResponse(nullptr) {}
  ~PetitionResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PetitionResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PetitionResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PetitionResponse(::google::protobuf::internal::ConstantInitialized);

  inline PetitionResponse(const PetitionResponse& from) : PetitionResponse(nullptr, from) {}
  inline PetitionResponse(PetitionResponse&& from) noexcept
      : PetitionResponse(nullptr, ::std::move(from)) {}
  inline PetitionResponse& operator=(const PetitionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PetitionResponse& operator=(PetitionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PetitionResponse& default_instance() {
    return *reinterpret_cast<const PetitionResponse*>(
        &_PetitionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(PetitionResponse& a, PetitionResponse& b) { a.Swap(&b); }
  inline void Swap(PetitionResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PetitionResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PetitionResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PetitionResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PetitionResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PetitionResponse& from) { PetitionResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PetitionResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game_api.v1.PetitionResponse"; }

  explicit PetitionResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PetitionResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PetitionResponse& from);
  PetitionResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PetitionResponse&& from) noexcept
      : PetitionResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRespondedFieldNumber = 1,
    kAcceptedFieldNumber = 2,
  };
  // bool responded = 1;
  void clear_responded() ;
  bool responded() const;
  void set_responded(bool value);

  private:
  bool _internal_responded() const;
  void _internal_set_responded(bool value);

  public:
  // bool accepted = 2;
  void clear_accepted() ;
  bool accepted() const;
  void set_accepted(bool value);

  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.PetitionResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PetitionResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool responded_;
    bool accepted_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PetitionResponse_class_data_;
// -------------------------------------------------------------------

class GameState_ResourcesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::int32_t, ::int32_t,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::int32_t, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  GameState_ResourcesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameState_ResourcesEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit GameState_ResourcesEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_GameState_ResourcesEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_api_5ftypes_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull GameState_ResourcesEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class GameState_BuildingCountsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::int32_t, ::int32_t,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::int32_t, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  GameState_BuildingCountsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameState_BuildingCountsEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit GameState_BuildingCountsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_GameState_BuildingCountsEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_api_5ftypes_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull GameState_BuildingCountsEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class UIAction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game_api.v1.UIAction) */ {
 public:
  inline UIAction() : UIAction(nullptr) {}
  ~UIAction() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UIAction* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UIAction));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UIAction(::google::protobuf::internal::ConstantInitialized);

  inline UIAction(const UIAction& from) : UIAction(nullptr, from) {}
  inline UIAction(UIAction&& from) noexcept
      : UIAction(nullptr, ::std::move(from)) {}
  inline UIAction& operator=(const UIAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline UIAction& operator=(UIAction&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UIAction& default_instance() {
    return *reinterpret_cast<const UIAction*>(
        &_UIAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(UIAction& a, UIAction& b) { a.Swap(&b); }
  inline void Swap(UIAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UIAction* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UIAction* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UIAction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UIAction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UIAction& from) { UIAction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UIAction* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game_api.v1.UIAction"; }

  explicit UIAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UIAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UIAction& from);
  UIAction(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UIAction&& from) noexcept
      : UIAction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPetitionResponseFieldNumber = 1,
    kSaveGameFieldNumber = 2,
  };
  // .game_api.v1.PetitionResponse petition_response = 1;
  bool has_petition_response() const;
  void clear_petition_response() ;
  const ::game_api::v1::PetitionResponse& petition_response() const;
  [[nodiscard]] ::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE release_petition_response();
  ::game_api::v1::PetitionResponse* PROTOBUF_NONNULL mutable_petition_response();
  void set_allocated_petition_response(::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_petition_response(::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE value);
  ::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE unsafe_arena_release_petition_response();

  private:
  const ::game_api::v1::PetitionResponse& _internal_petition_response() const;
  ::game_api::v1::PetitionResponse* PROTOBUF_NONNULL _internal_mutable_petition_response();

  public:
  // bool save_game = 2;
  void clear_save_game() ;
  bool save_game() const;
  void set_save_game(bool value);

  private:
  bool _internal_save_game() const;
  void _internal_set_save_game(bool value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.UIAction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UIAction& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE petition_response_;
    bool save_game_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UIAction_class_data_;
// -------------------------------------------------------------------

class Building final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game_api.v1.Building) */ {
 public:
  inline Building() : Building(nullptr) {}
  ~Building() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Building* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Building));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Building(::google::protobuf::internal::ConstantInitialized);

  inline Building(const Building& from) : Building(nullptr, from) {}
  inline Building(Building&& from) noexcept
      : Building(nullptr, ::std::move(from)) {}
  inline Building& operator=(const Building& from) {
    CopyFrom(from);
    return *this;
  }
  inline Building& operator=(Building&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Building& default_instance() {
    return *reinterpret_cast<const Building*>(
        &_Building_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Building& a, Building& b) { a.Swap(&b); }
  inline void Swap(Building* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Building* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Building* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Building>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Building& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Building& from) { Building::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Building* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game_api.v1.Building"; }

  explicit Building(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Building(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Building& from);
  Building(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Building&& from) noexcept
      : Building(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEffectsFieldNumber = 4,
    kTypeFieldNumber = 1,
    kBuildCostFieldNumber = 2,
    kTicksToCompleteFieldNumber = 3,
  };
  // repeated .game_api.v1.ResourceEffect effects = 4;
  int effects_size() const;
  private:
  int _internal_effects_size() const;

  public:
  void clear_effects() ;
  ::game_api::v1::ResourceEffect* PROTOBUF_NONNULL mutable_effects(int index);
  ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>* PROTOBUF_NONNULL mutable_effects();

  private:
  const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>& _internal_effects() const;
  ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>* PROTOBUF_NONNULL _internal_mutable_effects();
  public:
  const ::game_api::v1::ResourceEffect& effects(int index) const;
  ::game_api::v1::ResourceEffect* PROTOBUF_NONNULL add_effects();
  const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>& effects() const;
  // .game_api.v1.BuildingType type = 1;
  void clear_type() ;
  ::game_api::v1::BuildingType type() const;
  void set_type(::game_api::v1::BuildingType value);

  private:
  ::game_api::v1::BuildingType _internal_type() const;
  void _internal_set_type(::game_api::v1::BuildingType value);

  public:
  // int32 build_cost = 2;
  void clear_build_cost() ;
  ::int32_t build_cost() const;
  void set_build_cost(::int32_t value);

  private:
  ::int32_t _internal_build_cost() const;
  void _internal_set_build_cost(::int32_t value);

  public:
  // int32 ticks_to_complete = 3;
  void clear_ticks_to_complete() ;
  ::int32_t ticks_to_complete() const;
  void set_ticks_to_complete(::int32_t value);

  private:
  ::int32_t _internal_ticks_to_complete() const;
  void _internal_set_ticks_to_complete(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.Building)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Building& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::game_api::v1::ResourceEffect > effects_;
    int type_;
    ::int32_t build_cost_;
    ::int32_t ticks_to_complete_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Building_class_data_;
// -------------------------------------------------------------------

class Petition final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game_api.v1.Petition) */ {
 public:
  inline Petition() : Petition(nullptr) {}
  ~Petition() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Petition* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Petition));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Petition(::google::protobuf::internal::ConstantInitialized);

  inline Petition(const Petition& from) : Petition(nullptr, from) {}
  inline Petition(Petition&& from) noexcept
      : Petition(nullptr, ::std::move(from)) {}
  inline Petition& operator=(const Petition& from) {
    CopyFrom(from);
    return *this;
  }
  inline Petition& operator=(Petition&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Petition& default_instance() {
    return *reinterpret_cast<const Petition*>(
        &_Petition_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Petition& a, Petition& b) { a.Swap(&b); }
  inline void Swap(Petition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Petition* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Petition* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Petition>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Petition& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Petition& from) { Petition::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Petition* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game_api.v1.Petition"; }

  explicit Petition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Petition(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Petition& from);
  Petition(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Petition&& from) noexcept
      : Petition(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBuildingFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // .game_api.v1.Building building = 2;
  bool has_building() const;
  void clear_building() ;
  const ::game_api::v1::Building& building() const;
  [[nodiscard]] ::game_api::v1::Building* PROTOBUF_NULLABLE release_building();
  ::game_api::v1::Building* PROTOBUF_NONNULL mutable_building();
  void set_allocated_building(::game_api::v1::Building* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_building(::game_api::v1::Building* PROTOBUF_NULLABLE value);
  ::game_api::v1::Building* PROTOBUF_NULLABLE unsafe_arena_release_building();

  private:
  const ::game_api::v1::Building& _internal_building() const;
  ::game_api::v1::Building* PROTOBUF_NONNULL _internal_mutable_building();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.Petition)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Petition& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::game_api::v1::Building* PROTOBUF_NULLABLE building_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Petition_class_data_;
// -------------------------------------------------------------------

class GameState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game_api.v1.GameState) */ {
 public:
  inline GameState() : GameState(nullptr) {}
  ~GameState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GameState* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GameState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameState(::google::protobuf::internal::ConstantInitialized);

  inline GameState(const GameState& from) : GameState(nullptr, from) {}
  inline GameState(GameState&& from) noexcept
      : GameState(nullptr, ::std::move(from)) {}
  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameState& operator=(GameState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameState& default_instance() {
    return *reinterpret_cast<const GameState*>(
        &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(GameState& a, GameState& b) { a.Swap(&b); }
  inline void Swap(GameState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GameState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GameState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GameState& from) { GameState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GameState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game_api.v1.GameState"; }

  explicit GameState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GameState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GameState& from);
  GameState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GameState&& from) noexcept
      : GameState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentPetitionFieldNumber = 4,
    kBuildingCountsFieldNumber = 1,
    kResourcesFieldNumber = 5,
  };
  // .game_api.v1.Petition current_petition = 4;
  bool has_current_petition() const;
  void clear_current_petition() ;
  const ::game_api::v1::Petition& current_petition() const;
  [[nodiscard]] ::game_api::v1::Petition* PROTOBUF_NULLABLE release_current_petition();
  ::game_api::v1::Petition* PROTOBUF_NONNULL mutable_current_petition();
  void set_allocated_current_petition(::game_api::v1::Petition* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_current_petition(::game_api::v1::Petition* PROTOBUF_NULLABLE value);
  ::game_api::v1::Petition* PROTOBUF_NULLABLE unsafe_arena_release_current_petition();

  private:
  const ::game_api::v1::Petition& _internal_current_petition() const;
  ::game_api::v1::Petition* PROTOBUF_NONNULL _internal_mutable_current_petition();

  public:
  // map<int32, int32> building_counts = 1;
  int building_counts_size() const;
  private:
  int _internal_building_counts_size() const;

  public:
  void clear_building_counts() ;
  const ::google::protobuf::Map<::int32_t, ::int32_t>& building_counts() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL mutable_building_counts();

  private:
  const ::google::protobuf::Map<::int32_t, ::int32_t>& _internal_building_counts() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL _internal_mutable_building_counts();

  public:
  // map<int32, int32> resources = 5;
  int resources_size() const;
  private:
  int _internal_resources_size() const;

  public:
  void clear_resources() ;
  const ::google::protobuf::Map<::int32_t, ::int32_t>& resources() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL mutable_resources();

  private:
  const ::google::protobuf::Map<::int32_t, ::int32_t>& _internal_resources() const;
  ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL _internal_mutable_resources();

  public:
  // @@protoc_insertion_point(class_scope:game_api.v1.GameState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GameState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::game_api::v1::Petition* PROTOBUF_NULLABLE current_petition_;
    ::google::protobuf::internal::MapField<GameState_BuildingCountsEntry_DoNotUse, ::int32_t, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        building_counts_;
    ::google::protobuf::internal::MapField<GameState_ResourcesEntry_DoNotUse, ::int32_t, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        resources_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_5ftypes_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GameState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ResourceEffect

// .game_api.v1.ResourceType resource_type = 1;
inline void ResourceEffect::clear_resource_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resource_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::game_api::v1::ResourceType ResourceEffect::resource_type() const {
  // @@protoc_insertion_point(field_get:game_api.v1.ResourceEffect.resource_type)
  return _internal_resource_type();
}
inline void ResourceEffect::set_resource_type(::game_api::v1::ResourceType value) {
  _internal_set_resource_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:game_api.v1.ResourceEffect.resource_type)
}
inline ::game_api::v1::ResourceType ResourceEffect::_internal_resource_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::game_api::v1::ResourceType>(_impl_.resource_type_);
}
inline void ResourceEffect::_internal_set_resource_type(::game_api::v1::ResourceType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resource_type_ = value;
}

// int32 delta_value = 2;
inline void ResourceEffect::clear_delta_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delta_value_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t ResourceEffect::delta_value() const {
  // @@protoc_insertion_point(field_get:game_api.v1.ResourceEffect.delta_value)
  return _internal_delta_value();
}
inline void ResourceEffect::set_delta_value(::int32_t value) {
  _internal_set_delta_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:game_api.v1.ResourceEffect.delta_value)
}
inline ::int32_t ResourceEffect::_internal_delta_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.delta_value_;
}
inline void ResourceEffect::_internal_set_delta_value(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delta_value_ = value;
}

// -------------------------------------------------------------------

// Building

// .game_api.v1.BuildingType type = 1;
inline void Building::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::game_api::v1::BuildingType Building::type() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.type)
  return _internal_type();
}
inline void Building::set_type(::game_api::v1::BuildingType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:game_api.v1.Building.type)
}
inline ::game_api::v1::BuildingType Building::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::game_api::v1::BuildingType>(_impl_.type_);
}
inline void Building::_internal_set_type(::game_api::v1::BuildingType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// int32 build_cost = 2;
inline void Building::clear_build_cost() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.build_cost_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Building::build_cost() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.build_cost)
  return _internal_build_cost();
}
inline void Building::set_build_cost(::int32_t value) {
  _internal_set_build_cost(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:game_api.v1.Building.build_cost)
}
inline ::int32_t Building::_internal_build_cost() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.build_cost_;
}
inline void Building::_internal_set_build_cost(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.build_cost_ = value;
}

// int32 ticks_to_complete = 3;
inline void Building::clear_ticks_to_complete() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ticks_to_complete_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t Building::ticks_to_complete() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.ticks_to_complete)
  return _internal_ticks_to_complete();
}
inline void Building::set_ticks_to_complete(::int32_t value) {
  _internal_set_ticks_to_complete(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:game_api.v1.Building.ticks_to_complete)
}
inline ::int32_t Building::_internal_ticks_to_complete() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ticks_to_complete_;
}
inline void Building::_internal_set_ticks_to_complete(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ticks_to_complete_ = value;
}

// repeated .game_api.v1.ResourceEffect effects = 4;
inline int Building::_internal_effects_size() const {
  return _internal_effects().size();
}
inline int Building::effects_size() const {
  return _internal_effects_size();
}
inline void Building::clear_effects() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.effects_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::game_api::v1::ResourceEffect* PROTOBUF_NONNULL Building::mutable_effects(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:game_api.v1.Building.effects)
  return _internal_mutable_effects()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>* PROTOBUF_NONNULL Building::mutable_effects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:game_api.v1.Building.effects)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_effects();
}
inline const ::game_api::v1::ResourceEffect& Building::effects(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.Building.effects)
  return _internal_effects().Get(index);
}
inline ::game_api::v1::ResourceEffect* PROTOBUF_NONNULL Building::add_effects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::game_api::v1::ResourceEffect* _add =
      _internal_mutable_effects()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:game_api.v1.Building.effects)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>& Building::effects() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:game_api.v1.Building.effects)
  return _internal_effects();
}
inline const ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>&
Building::_internal_effects() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.effects_;
}
inline ::google::protobuf::RepeatedPtrField<::game_api::v1::ResourceEffect>* PROTOBUF_NONNULL
Building::_internal_mutable_effects() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.effects_;
}

// -------------------------------------------------------------------

// Petition

// int32 id = 1;
inline void Petition::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t Petition::id() const {
  // @@protoc_insertion_point(field_get:game_api.v1.Petition.id)
  return _internal_id();
}
inline void Petition::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:game_api.v1.Petition.id)
}
inline ::int32_t Petition::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Petition::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// .game_api.v1.Building building = 2;
inline bool Petition::has_building() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.building_ != nullptr);
  return value;
}
inline void Petition::clear_building() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.building_ != nullptr) _impl_.building_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::game_api::v1::Building& Petition::_internal_building() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::game_api::v1::Building* p = _impl_.building_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_api::v1::Building&>(::game_api::v1::_Building_default_instance_);
}
inline const ::game_api::v1::Building& Petition::building() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.Petition.building)
  return _internal_building();
}
inline void Petition::unsafe_arena_set_allocated_building(
    ::game_api::v1::Building* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.building_);
  }
  _impl_.building_ = reinterpret_cast<::game_api::v1::Building*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_api.v1.Petition.building)
}
inline ::game_api::v1::Building* PROTOBUF_NULLABLE Petition::release_building() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::Building* released = _impl_.building_;
  _impl_.building_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::game_api::v1::Building* PROTOBUF_NULLABLE Petition::unsafe_arena_release_building() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:game_api.v1.Petition.building)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::Building* temp = _impl_.building_;
  _impl_.building_ = nullptr;
  return temp;
}
inline ::game_api::v1::Building* PROTOBUF_NONNULL Petition::_internal_mutable_building() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.building_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::game_api::v1::Building>(GetArena());
    _impl_.building_ = reinterpret_cast<::game_api::v1::Building*>(p);
  }
  return _impl_.building_;
}
inline ::game_api::v1::Building* PROTOBUF_NONNULL Petition::mutable_building()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::Building* _msg = _internal_mutable_building();
  // @@protoc_insertion_point(field_mutable:game_api.v1.Petition.building)
  return _msg;
}
inline void Petition::set_allocated_building(::game_api::v1::Building* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.building_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.building_ = reinterpret_cast<::game_api::v1::Building*>(value);
  // @@protoc_insertion_point(field_set_allocated:game_api.v1.Petition.building)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// GameState

// map<int32, int32> building_counts = 1;
inline int GameState::_internal_building_counts_size() const {
  return _internal_building_counts().size();
}
inline int GameState::building_counts_size() const {
  return _internal_building_counts_size();
}
inline void GameState::clear_building_counts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.building_counts_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::_internal_building_counts() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.building_counts_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::building_counts() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:game_api.v1.GameState.building_counts)
  return _internal_building_counts();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL GameState::_internal_mutable_building_counts() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.building_counts_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL GameState::mutable_building_counts()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_map:game_api.v1.GameState.building_counts)
  return _internal_mutable_building_counts();
}

// map<int32, int32> resources = 5;
inline int GameState::_internal_resources_size() const {
  return _internal_resources().size();
}
inline int GameState::resources_size() const {
  return _internal_resources_size();
}
inline void GameState::clear_resources() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resources_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::_internal_resources() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resources_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::int32_t>& GameState::resources() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:game_api.v1.GameState.resources)
  return _internal_resources();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL GameState::_internal_mutable_resources() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.resources_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::int32_t>* PROTOBUF_NONNULL GameState::mutable_resources()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_map:game_api.v1.GameState.resources)
  return _internal_mutable_resources();
}

// .game_api.v1.Petition current_petition = 4;
inline bool GameState::has_current_petition() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.current_petition_ != nullptr);
  return value;
}
inline void GameState::clear_current_petition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.current_petition_ != nullptr) _impl_.current_petition_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::game_api::v1::Petition& GameState::_internal_current_petition() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::game_api::v1::Petition* p = _impl_.current_petition_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_api::v1::Petition&>(::game_api::v1::_Petition_default_instance_);
}
inline const ::game_api::v1::Petition& GameState::current_petition() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.GameState.current_petition)
  return _internal_current_petition();
}
inline void GameState::unsafe_arena_set_allocated_current_petition(
    ::game_api::v1::Petition* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.current_petition_);
  }
  _impl_.current_petition_ = reinterpret_cast<::game_api::v1::Petition*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_api.v1.GameState.current_petition)
}
inline ::game_api::v1::Petition* PROTOBUF_NULLABLE GameState::release_current_petition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::Petition* released = _impl_.current_petition_;
  _impl_.current_petition_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::game_api::v1::Petition* PROTOBUF_NULLABLE GameState::unsafe_arena_release_current_petition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:game_api.v1.GameState.current_petition)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::Petition* temp = _impl_.current_petition_;
  _impl_.current_petition_ = nullptr;
  return temp;
}
inline ::game_api::v1::Petition* PROTOBUF_NONNULL GameState::_internal_mutable_current_petition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.current_petition_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::game_api::v1::Petition>(GetArena());
    _impl_.current_petition_ = reinterpret_cast<::game_api::v1::Petition*>(p);
  }
  return _impl_.current_petition_;
}
inline ::game_api::v1::Petition* PROTOBUF_NONNULL GameState::mutable_current_petition()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::Petition* _msg = _internal_mutable_current_petition();
  // @@protoc_insertion_point(field_mutable:game_api.v1.GameState.current_petition)
  return _msg;
}
inline void GameState::set_allocated_current_petition(::game_api::v1::Petition* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.current_petition_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.current_petition_ = reinterpret_cast<::game_api::v1::Petition*>(value);
  // @@protoc_insertion_point(field_set_allocated:game_api.v1.GameState.current_petition)
}

// -------------------------------------------------------------------

// PetitionResponse

// bool responded = 1;
inline void PetitionResponse::clear_responded() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.responded_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool PetitionResponse::responded() const {
  // @@protoc_insertion_point(field_get:game_api.v1.PetitionResponse.responded)
  return _internal_responded();
}
inline void PetitionResponse::set_responded(bool value) {
  _internal_set_responded(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:game_api.v1.PetitionResponse.responded)
}
inline bool PetitionResponse::_internal_responded() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.responded_;
}
inline void PetitionResponse::_internal_set_responded(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.responded_ = value;
}

// bool accepted = 2;
inline void PetitionResponse::clear_accepted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accepted_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool PetitionResponse::accepted() const {
  // @@protoc_insertion_point(field_get:game_api.v1.PetitionResponse.accepted)
  return _internal_accepted();
}
inline void PetitionResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:game_api.v1.PetitionResponse.accepted)
}
inline bool PetitionResponse::_internal_accepted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accepted_;
}
inline void PetitionResponse::_internal_set_accepted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accepted_ = value;
}

// -------------------------------------------------------------------

// UIAction

// .game_api.v1.PetitionResponse petition_response = 1;
inline bool UIAction::has_petition_response() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.petition_response_ != nullptr);
  return value;
}
inline void UIAction::clear_petition_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.petition_response_ != nullptr) _impl_.petition_response_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::game_api::v1::PetitionResponse& UIAction::_internal_petition_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::game_api::v1::PetitionResponse* p = _impl_.petition_response_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_api::v1::PetitionResponse&>(::game_api::v1::_PetitionResponse_default_instance_);
}
inline const ::game_api::v1::PetitionResponse& UIAction::petition_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game_api.v1.UIAction.petition_response)
  return _internal_petition_response();
}
inline void UIAction::unsafe_arena_set_allocated_petition_response(
    ::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.petition_response_);
  }
  _impl_.petition_response_ = reinterpret_cast<::game_api::v1::PetitionResponse*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_api.v1.UIAction.petition_response)
}
inline ::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE UIAction::release_petition_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::PetitionResponse* released = _impl_.petition_response_;
  _impl_.petition_response_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE UIAction::unsafe_arena_release_petition_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:game_api.v1.UIAction.petition_response)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::PetitionResponse* temp = _impl_.petition_response_;
  _impl_.petition_response_ = nullptr;
  return temp;
}
inline ::game_api::v1::PetitionResponse* PROTOBUF_NONNULL UIAction::_internal_mutable_petition_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.petition_response_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::game_api::v1::PetitionResponse>(GetArena());
    _impl_.petition_response_ = reinterpret_cast<::game_api::v1::PetitionResponse*>(p);
  }
  return _impl_.petition_response_;
}
inline ::game_api::v1::PetitionResponse* PROTOBUF_NONNULL UIAction::mutable_petition_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::game_api::v1::PetitionResponse* _msg = _internal_mutable_petition_response();
  // @@protoc_insertion_point(field_mutable:game_api.v1.UIAction.petition_response)
  return _msg;
}
inline void UIAction::set_allocated_petition_response(::game_api::v1::PetitionResponse* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.petition_response_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.petition_response_ = reinterpret_cast<::game_api::v1::PetitionResponse*>(value);
  // @@protoc_insertion_point(field_set_allocated:game_api.v1.UIAction.petition_response)
}

// bool save_game = 2;
inline void UIAction::clear_save_game() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.save_game_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool UIAction::save_game() const {
  // @@protoc_insertion_point(field_get:game_api.v1.UIAction.save_game)
  return _internal_save_game();
}
inline void UIAction::set_save_game(bool value) {
  _internal_set_save_game(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:game_api.v1.UIAction.save_game)
}
inline bool UIAction::_internal_save_game() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.save_game_;
}
inline void UIAction::_internal_set_save_game(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.save_game_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace game_api


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::game_api::v1::BuildingType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::game_api::v1::BuildingType>() {
  return ::game_api::v1::BuildingType_descriptor();
}
template <>
struct is_proto_enum<::game_api::v1::ResourceType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::game_api::v1::ResourceType>() {
  return ::game_api::v1::ResourceType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // api_5ftypes_2eproto_2epb_2eh
